/**
 * Mapping of countries to their currency codes
 * Used for auto-selecting currency when a country is chosen
 */
export const countryCurrencyMap: Record<string, string> = {
  // Middle East
  "United Arab Emirates": "AED",
  "Saudi Arabia": "SAR",
  "Qatar": "QAR",
  "Kuwait": "KWD",
  "Bahrain": "BHD",
  "Oman": "OMR",
  "Yemen": "YER",
  "Lebanon": "LBP",
  "Syria": "SYP",
  "Jordan": "JOD",
  "Palestine": "ILS",
  "Israel": "ILS",
  "Turkey": "TRY",
  "Iran": "IRR",
  "Iraq": "IQD",

  // Europe
  "United Kingdom": "GBP",
  "Ireland": "EUR",
  "France": "EUR",
  "Germany": "EUR",
  "Italy": "EUR",
  "Spain": "EUR",
  "Portugal": "EUR",
  "Greece": "EUR",
  "Netherlands": "EUR",
  "Belgium": "EUR",
  "Austria": "EUR",
  "Switzerland": "CHF",
  "Sweden": "SEK",
  "Norway": "NOK",
  "Denmark": "DKK",
  "Finland": "EUR",
  "Poland": "PLN",
  "Czech Republic": "CZK",
  "Czechia": "CZK",
  "Hungary": "HUF",
  "Romania": "RON",
  "Bulgaria": "BGN",
  "Croatia": "HRK",
  "Serbia": "RSD",
  "Slovenia": "EUR",
  "Slovakia": "EUR",
  "Russia": "RUB",
  "Ukraine": "UAH",
  "Belarus": "BYN",
  "Moldova": "MDL",
  "Georgia": "GEL",
  "Armenia": "AMD",
  "Azerbaijan": "AZN",

  // Asia
  "China": "CNY",
  "Japan": "JPY",
  "South Korea": "KRW",
  "India": "INR",
  "Pakistan": "PKR",
  "Bangladesh": "BDT",
  "Sri Lanka": "LKR",
  "Thailand": "THB",
  "Vietnam": "VND",
  "Philippines": "PHP",
  "Indonesia": "IDR",
  "Malaysia": "MYR",
  "Singapore": "SGD",
  "Hong Kong": "HKD",
  "Taiwan": "TWD",
  "Myanmar": "MMK",
  "Cambodia": "KHR",
  "Laos": "LAK",
  "Mongolia": "MNT",
  "Kazakhstan": "KZT",
  "Uzbekistan": "UZS",
  "Turkmenistan": "TMT",
  "Tajikistan": "TJS",
  "Kyrgyzstan": "KGS",
  "Afghanistan": "AFN",
  "Nepal": "NPR",
  "Bhutan": "BTN",
  "Maldives": "MVR",

  // Americas
  "United States": "USD",
  "Canada": "CAD",
  "Mexico": "MXN",
  "Brazil": "BRL",
  "Argentina": "ARS",
  "Chile": "CLP",
  "Colombia": "COP",
  "Peru": "PEN",
  "Venezuela": "VES",
  "Ecuador": "USD",
  "Bolivia": "BOB",
  "Paraguay": "PYG",
  "Uruguay": "UYU",
  "Costa Rica": "CRC",
  "Panama": "PAB",
  "Guatemala": "GTQ",
  "Honduras": "HNL",
  "El Salvador": "SVC",
  "Nicaragua": "NIO",
  "Belize": "BZD",
  "Jamaica": "JMD",
  "Trinidad and Tobago": "TTD",
  "Bahamas": "BSD",
  "Barbados": "BBD",
  "Dominican Republic": "DOP",
  "Haiti": "HTG",
  "Cuba": "CUP",

  // Africa
  "Egypt": "EGP",
  "South Africa": "ZAR",
  "Nigeria": "NGN",
  "Kenya": "KES",
  "Ethiopia": "ETB",
  "Ghana": "GHS",
  "Morocco": "MAD",
  "Algeria": "DZD",
  "Tunisia": "TND",
  "Libya": "LYD",
  "Sudan": "SDG",
  "Tanzania": "TZS",
  "Uganda": "UGX",
  "Rwanda": "RWF",
  "Cameroon": "XAF",
  "Ivory Coast": "XOF",
  "Côte d'Ivoire": "XOF",
  "Senegal": "XOF",
  "Mali": "XOF",
  "Burkina Faso": "XOF",
  "Guinea": "GNF",
  "Sierra Leone": "SLL",
  "Liberia": "LRD",
  "Zambia": "ZMW",
  "Zimbabwe": "ZWL",
  "Botswana": "BWP",
  "Namibia": "NAD",
  "Lesotho": "LSL",
  "Eswatini": "SZL",
  "Mauritius": "MUR",
  "Seychelles": "SCR",
  "Madagascar": "MGA",
  "Mozambique": "MZN",
  "Malawi": "MWK",
  "Angola": "AOA",
  "Congo": "CDF",
  "Democratic Republic of the Congo": "CDF",

  // Oceania
  "Australia": "AUD",
  "New Zealand": "NZD",
  "Fiji": "FJD",
  "Papua New Guinea": "PGK",
  "Solomon Islands": "SBD",
  "Samoa": "WST",
  "Vanuatu": "VUV",
  "Kiribati": "AUD",
  "Tonga": "TOP",
  "Micronesia": "USD",
  "Palau": "USD",
  "Marshall Islands": "USD",
  "Nauru": "AUD",
  "Tuvalu": "AUD",
};

/**
 * Get currency code for a country
 * @param countryName - The name of the country
 * @returns The currency code (e.g., "AED", "USD", "EUR") or undefined if not found
 */
export function getCurrencyCodeForCountry(countryName: string): string | undefined {
  return countryCurrencyMap[countryName];
}
