export interface CarMakerData {
  name: string;
  country: string;
  popularModels: string[];
}

const globalMakers: CarMakerData[] = [
  { name: "Toyota", country: "Global", popularModels: ["Corolla", "Camry", "RAV4", "Hilux", "Land Cruiser", "Prado", "Yaris", "Prius", "Highlander", "4Runner", "Tacoma", "Tundra", "C-HR", "Avalon", "Supra", "Fortuner", "Vios", "Rush", "Avanza", "Innova"] },
  { name: "Honda", country: "Global", popularModels: ["Civic", "Accord", "CR-V", "HR-V", "City", "Jazz/Fit", "Pilot", "Odyssey", "Ridgeline", "Passport", "BR-V", "WR-V", "Amaze"] },
  { name: "Nissan", country: "Global", popularModels: ["Altima", "Sentra", "Rogue", "Pathfinder", "Murano", "Kicks", "X-Trail", "Patrol", "Sunny", "Frontier", "Titan", "Versa", "Maxima", "Navara", "Juke", "Qashqai", "Leaf"] },
  { name: "Hyundai", country: "Global", popularModels: ["Elantra", "Tucson", "Santa Fe", "Accent", "Sonata", "Kona", "Palisade", "Venue", "Creta", "i10", "i20", "i30", "Ioniq 5", "Ioniq 6", "Staria", "Bayon"] },
  { name: "Kia", country: "Global", popularModels: ["Sportage", "Seltos", "Sorento", "Forte/Cerato", "Rio", "Telluride", "Soul", "Carnival", "Picanto", "Stinger", "EV6", "EV9", "Niro", "K5/Optima", "Sonet"] },
  { name: "Ford", country: "Global", popularModels: ["F-150", "Ranger", "Explorer", "Escape", "Edge", "Bronco", "Mustang", "Maverick", "Expedition", "Transit", "Focus", "Fiesta", "EcoSport", "Everest", "Territory", "Puma"] },
  { name: "Chevrolet", country: "Global", popularModels: ["Silverado", "Equinox", "Traverse", "Tahoe", "Suburban", "Malibu", "Trax", "Blazer", "Colorado", "Camaro", "Corvette", "Spark", "Onix", "Captiva", "Trailblazer"] },
  { name: "BMW", country: "Global", popularModels: ["3 Series", "5 Series", "7 Series", "X1", "X3", "X5", "X7", "4 Series", "8 Series", "Z4", "iX", "i4", "i7", "X2", "X4", "X6", "2 Series", "1 Series"] },
  { name: "Mercedes-Benz", country: "Global", popularModels: ["C-Class", "E-Class", "S-Class", "GLC", "GLE", "GLA", "GLB", "GLS", "A-Class", "CLA", "CLS", "AMG GT", "EQS", "EQE", "EQB", "Sprinter", "V-Class", "G-Class"] },
  { name: "Audi", country: "Global", popularModels: ["A3", "A4", "A6", "A8", "Q3", "Q5", "Q7", "Q8", "e-tron", "TT", "R8", "A5", "A7", "Q2", "RS3", "RS5", "RS6", "RS7"] },
  { name: "Volkswagen", country: "Global", popularModels: ["Golf", "Jetta", "Passat", "Tiguan", "Atlas", "Taos", "Polo", "T-Roc", "T-Cross", "Touareg", "Arteon", "ID.4", "ID.3", "ID.Buzz", "Amarok", "Virtus"] },
  { name: "Tesla", country: "Global", popularModels: ["Model 3", "Model Y", "Model S", "Model X", "Cybertruck"] },
  { name: "Mazda", country: "Global", popularModels: ["Mazda3", "Mazda6", "CX-5", "CX-30", "CX-50", "CX-9", "CX-90", "MX-5 Miata", "CX-3", "CX-60", "CX-80"] },
  { name: "Subaru", country: "Global", popularModels: ["Outback", "Forester", "Crosstrek", "Impreza", "Ascent", "Legacy", "WRX", "BRZ", "Solterra"] },
  { name: "Lexus", country: "Global", popularModels: ["RX", "NX", "ES", "IS", "GX", "LX", "UX", "LC", "LS", "RC", "RZ"] },
  { name: "Volvo", country: "Global", popularModels: ["XC40", "XC60", "XC90", "S60", "S90", "V60", "V90", "C40", "EX30", "EX90"] },
  { name: "Land Rover", country: "Global", popularModels: ["Range Rover", "Range Rover Sport", "Range Rover Velar", "Range Rover Evoque", "Discovery", "Discovery Sport", "Defender"] },
  { name: "Jaguar", country: "Global", popularModels: ["F-Pace", "E-Pace", "I-Pace", "XE", "XF", "F-Type"] },
  { name: "Porsche", country: "Global", popularModels: ["Cayenne", "Macan", "911", "Taycan", "Panamera", "718 Boxster", "718 Cayman"] },
  { name: "Jeep", country: "Global", popularModels: ["Wrangler", "Grand Cherokee", "Cherokee", "Compass", "Renegade", "Gladiator", "Wagoneer", "Grand Wagoneer", "Avenger"] },
  { name: "Ram", country: "Global", popularModels: ["1500", "2500", "3500", "ProMaster"] },
  { name: "GMC", country: "Global", popularModels: ["Sierra", "Terrain", "Acadia", "Yukon", "Canyon", "Hummer EV"] },
  { name: "Dodge", country: "Global", popularModels: ["Charger", "Challenger", "Durango", "Hornet"] },
  { name: "Cadillac", country: "Global", popularModels: ["Escalade", "CT5", "CT4", "XT4", "XT5", "XT6", "Lyriq"] },
  { name: "Lincoln", country: "Global", popularModels: ["Navigator", "Aviator", "Corsair", "Nautilus"] },
  { name: "Chrysler", country: "Global", popularModels: ["Pacifica", "300"] },
  { name: "Buick", country: "Global", popularModels: ["Encore", "Encore GX", "Envision", "Enclave"] },
  { name: "Mitsubishi", country: "Global", popularModels: ["Outlander", "Eclipse Cross", "ASX/Outlander Sport", "Pajero", "L200/Triton", "Xpander", "Mirage", "Attrage"] },
  { name: "Suzuki", country: "Global", popularModels: ["Swift", "Vitara", "Jimny", "S-Cross", "Baleno", "Celerio", "Ertiga", "XL7", "Ignis", "Alto", "Wagon R", "Dzire", "Brezza"] },
  { name: "Peugeot", country: "Global", popularModels: ["208", "2008", "308", "3008", "408", "5008", "508", "Rifter", "Partner", "Landtrek"] },
  { name: "Renault", country: "Global", popularModels: ["Clio", "Captur", "Megane", "Kadjar", "Koleos", "Duster", "Logan", "Sandero", "Arkana", "Austral", "Scenic"] },
  { name: "Citroën", country: "Global", popularModels: ["C3", "C4", "C5 Aircross", "C3 Aircross", "Berlingo", "C5 X", "C4 X"] },
  { name: "Fiat", country: "Global", popularModels: ["500", "Panda", "Tipo", "500X", "500L", "Punto", "Doblo", "Toro", "Pulse", "Fastback"] },
  { name: "Alfa Romeo", country: "Global", popularModels: ["Giulia", "Stelvio", "Tonale", "Giulietta"] },
  { name: "SEAT/Cupra", country: "Global", popularModels: ["Ibiza", "Leon", "Arona", "Ateca", "Tarraco", "Cupra Formentor", "Cupra Born"] },
  { name: "Skoda", country: "Global", popularModels: ["Octavia", "Superb", "Kodiaq", "Karoq", "Kamiq", "Fabia", "Scala", "Enyaq"] },
  { name: "Opel/Vauxhall", country: "Global", popularModels: ["Corsa", "Astra", "Mokka", "Crossland", "Grandland", "Insignia", "Combo"] },
  { name: "MG", country: "Global", popularModels: ["ZS", "HS", "MG5", "MG4", "RX5", "Hector", "Gloster"] },
  { name: "Genesis", country: "Global", popularModels: ["G70", "G80", "G90", "GV60", "GV70", "GV80"] },
  { name: "Infiniti", country: "Global", popularModels: ["Q50", "Q60", "QX50", "QX55", "QX60", "QX80"] },
  { name: "Acura", country: "Global", popularModels: ["Integra", "TLX", "MDX", "RDX", "ZDX"] },
  { name: "Maserati", country: "Global", popularModels: ["Ghibli", "Levante", "Quattroporte", "MC20", "Grecale", "GranTurismo"] },
  { name: "Bentley", country: "Global", popularModels: ["Continental GT", "Flying Spur", "Bentayga"] },
  { name: "Rolls-Royce", country: "Global", popularModels: ["Ghost", "Phantom", "Cullinan", "Spectre", "Dawn", "Wraith"] },
  { name: "Ferrari", country: "Global", popularModels: ["Roma", "F8 Tributo", "SF90 Stradale", "296 GTB", "812 Superfast", "Purosangue"] },
  { name: "Lamborghini", country: "Global", popularModels: ["Urus", "Huracán", "Revuelto"] },
  { name: "Aston Martin", country: "Global", popularModels: ["DB12", "Vantage", "DBS", "DBX"] },
  { name: "McLaren", country: "Global", popularModels: ["720S", "GT", "Artura", "750S"] },
  { name: "Mini", country: "Global", popularModels: ["Cooper", "Countryman", "Clubman", "Paceman"] },
  { name: "smart", country: "Global", popularModels: ["#1", "#3", "EQ fortwo", "EQ forfour"] },
  { name: "Polestar", country: "Global", popularModels: ["Polestar 2", "Polestar 3", "Polestar 4"] },
  { name: "Rivian", country: "Global", popularModels: ["R1T", "R1S"] },
  { name: "Lucid", country: "Global", popularModels: ["Air", "Gravity"] },
  { name: "BYD", country: "Global", popularModels: ["Atto 3", "Seal", "Dolphin", "Han", "Tang", "Song Plus", "Yuan Plus"] },
  { name: "Geely", country: "Global", popularModels: ["Coolray", "Azkarra", "Emgrand", "Monjaro", "Okavango", "Xingyue L"] },
  { name: "Chery", country: "Global", popularModels: ["Tiggo 7 Pro", "Tiggo 8 Pro", "Arrizo 6", "Omoda 5", "Jaecoo J7"] },
  { name: "GWM/Haval", country: "Global", popularModels: ["H6", "Jolion", "Dargo", "Poer/Cannon", "H9", "Tank 300", "Tank 500"] },
  { name: "GAC", country: "Global", popularModels: ["GS4", "GS8", "Aion S", "Aion Y", "Emkoo", "M8"] },
  { name: "NIO", country: "Global", popularModels: ["ES8", "ES6", "EC6", "ET7", "ET5", "EC7"] },
  { name: "XPeng", country: "Global", popularModels: ["P7", "G9", "G6", "P5", "G3"] },
  { name: "Jetour", country: "Global", popularModels: ["X70", "T2", "Dashing", "X90"] },
  { name: "Changan", country: "Global", popularModels: ["CS75 Plus", "CS55 Plus", "CS35 Plus", "Uni-T", "Uni-K", "Uni-V", "Eado"] },
  { name: "BAIC", country: "Global", popularModels: ["X55", "X35", "D50", "BJ40", "EU5"] },
  { name: "Isuzu", country: "Global", popularModels: ["D-Max", "MU-X"] },
  { name: "Mahindra", country: "Global", popularModels: ["XUV700", "Thar", "Scorpio", "XUV400", "Bolero", "XUV300"] },
  { name: "Tata", country: "Global", popularModels: ["Nexon", "Harrier", "Safari", "Punch", "Tiago", "Altroz"] },
  { name: "Maruti Suzuki", country: "Global", popularModels: ["Swift", "Baleno", "Brezza", "Ertiga", "Wagon R", "Alto", "Dzire", "Grand Vitara", "Fronx", "Jimny", "Invicto"] },
  { name: "SsangYong/KGM", country: "Global", popularModels: ["Torres", "Rexton", "Korando", "Tivoli", "Musso"] },
  { name: "Proton", country: "Global", popularModels: ["X50", "X70", "Saga", "Persona", "Iriz", "Exora"] },
  { name: "Perodua", country: "Global", popularModels: ["Myvi", "Ativa", "Aruz", "Bezza", "Axia", "Alza"] },
  { name: "Dacia", country: "Global", popularModels: ["Sandero", "Duster", "Jogger", "Spring", "Logan"] },
  { name: "Lancia", country: "Global", popularModels: ["Ypsilon"] },
  { name: "DS Automobiles", country: "Global", popularModels: ["DS 3", "DS 4", "DS 7", "DS 9"] },
  { name: "Cupra", country: "Global", popularModels: ["Formentor", "Born", "Leon", "Ateca", "Tavascan"] },
];

export const carMakersByCountry: Record<string, CarMakerData[]> = {
  "Lebanon": [
    { name: "Toyota", country: "Lebanon", popularModels: ["Hilux", "Land Cruiser", "Corolla", "Camry", "RAV4", "Yaris", "Prado", "Fortuner"] },
    { name: "Nissan", country: "Lebanon", popularModels: ["Sunny", "Patrol", "X-Trail", "Kicks", "Altima", "Navara"] },
    { name: "Kia", country: "Lebanon", popularModels: ["Sportage", "Cerato", "Rio", "Sorento", "Picanto", "Seltos"] },
    { name: "Hyundai", country: "Lebanon", popularModels: ["Elantra", "Tucson", "Santa Fe", "Accent", "Creta", "Kona"] },
    { name: "Suzuki", country: "Lebanon", popularModels: ["Swift", "Vitara", "Jimny", "Celerio", "Ertiga", "S-Cross"] },
    { name: "Mitsubishi", country: "Lebanon", popularModels: ["Pajero", "Outlander", "Lancer", "ASX", "L200", "Eclipse Cross"] },
    { name: "Honda", country: "Lebanon", popularModels: ["Civic", "Accord", "CR-V", "HR-V", "City"] },
    { name: "Mazda", country: "Lebanon", popularModels: ["CX-5", "Mazda3", "CX-9", "Mazda6", "CX-3", "CX-30"] },
    { name: "Chevrolet", country: "Lebanon", popularModels: ["Tahoe", "Suburban", "Silverado", "Equinox", "Traverse"] },
    { name: "Ford", country: "Lebanon", popularModels: ["F-150", "Explorer", "Edge", "Escape", "Ranger"] },
    { name: "Mercedes-Benz", country: "Lebanon", popularModels: ["C-Class", "E-Class", "GLC", "GLE", "S-Class", "A-Class"] },
    { name: "BMW", country: "Lebanon", popularModels: ["3 Series", "5 Series", "X3", "X5", "X1"] },
  ],
  
  "United Arab Emirates": [
    { name: "Toyota", country: "United Arab Emirates", popularModels: ["Hilux", "Land Cruiser", "Corolla", "Camry", "RAV4", "Prado", "Fortuner", "Yaris"] },
    { name: "Nissan", country: "United Arab Emirates", popularModels: ["Patrol", "Sunny", "X-Trail", "Altima", "Kicks", "Pathfinder"] },
    { name: "Mitsubishi", country: "United Arab Emirates", popularModels: ["Pajero", "Outlander", "ASX", "L200", "Eclipse Cross"] },
    { name: "MG", country: "United Arab Emirates", popularModels: ["ZS", "HS", "RX5", "MG5", "MG4"] },
    { name: "Hyundai", country: "United Arab Emirates", popularModels: ["Tucson", "Elantra", "Santa Fe", "Creta", "Accent", "Kona", "Palisade"] },
    { name: "Ford", country: "United Arab Emirates", popularModels: ["F-150", "Explorer", "Edge", "Mustang", "Ranger", "Bronco", "Expedition"] },
    { name: "Kia", country: "United Arab Emirates", popularModels: ["Sportage", "Cerato", "Sorento", "Picanto", "Seltos", "Carnival", "Telluride"] },
    { name: "Land Rover", country: "United Arab Emirates", popularModels: ["Range Rover", "Discovery", "Defender", "Range Rover Sport", "Evoque", "Velar"] },
    { name: "Chevrolet", country: "United Arab Emirates", popularModels: ["Tahoe", "Suburban", "Silverado", "Traverse", "Equinox", "Blazer"] },
    { name: "Mercedes-Benz", country: "United Arab Emirates", popularModels: ["C-Class", "E-Class", "GLE", "GLC", "S-Class", "G-Class", "A-Class", "AMG GT"] },
    { name: "BMW", country: "United Arab Emirates", popularModels: ["X5", "3 Series", "5 Series", "X3", "7 Series", "X7", "4 Series"] },
    { name: "Tesla", country: "United Arab Emirates", popularModels: ["Model 3", "Model Y", "Model S", "Model X"] },
    { name: "Jetour", country: "United Arab Emirates", popularModels: ["T2", "X70", "Dashing"] },
    { name: "Lexus", country: "United Arab Emirates", popularModels: ["RX", "LX", "ES", "NX", "GX", "IS", "LC"] },
    { name: "Porsche", country: "United Arab Emirates", popularModels: ["Cayenne", "911", "Macan", "Taycan", "Panamera"] },
    { name: "GMC", country: "United Arab Emirates", popularModels: ["Sierra", "Yukon", "Terrain", "Acadia"] },
    { name: "Jeep", country: "United Arab Emirates", popularModels: ["Wrangler", "Grand Cherokee", "Gladiator", "Compass"] },
    { name: "Genesis", country: "United Arab Emirates", popularModels: ["G70", "G80", "GV70", "GV80"] },
    { name: "Chery", country: "United Arab Emirates", popularModels: ["Tiggo 7 Pro", "Tiggo 8 Pro", "Arrizo 6"] },
    { name: "GWM/Haval", country: "United Arab Emirates", popularModels: ["H6", "Jolion", "Dargo", "Tank 300"] },
  ],
  
  "United States": [
    { name: "Ford", country: "United States", popularModels: ["F-150", "F-250", "F-350", "Explorer", "Escape", "Mustang", "Edge", "Bronco", "Ranger", "Maverick", "Transit", "Expedition"] },
    { name: "Chevrolet", country: "United States", popularModels: ["Silverado", "Equinox", "Traverse", "Tahoe", "Suburban", "Malibu", "Blazer", "Trax", "Colorado", "Camaro", "Corvette"] },
    { name: "Toyota", country: "United States", popularModels: ["RAV4", "Camry", "Corolla", "Highlander", "Tacoma", "Tundra", "4Runner", "Prius", "Sienna", "Venza", "GR86", "Sequoia"] },
    { name: "Honda", country: "United States", popularModels: ["CR-V", "Civic", "Accord", "Pilot", "HR-V", "Odyssey", "Ridgeline", "Passport"] },
    { name: "Ram", country: "United States", popularModels: ["1500", "2500", "3500", "ProMaster"] },
    { name: "GMC", country: "United States", popularModels: ["Sierra", "Terrain", "Acadia", "Yukon", "Canyon", "Hummer EV"] },
    { name: "Tesla", country: "United States", popularModels: ["Model Y", "Model 3", "Model S", "Model X", "Cybertruck"] },
    { name: "Nissan", country: "United States", popularModels: ["Rogue", "Altima", "Sentra", "Pathfinder", "Kicks", "Frontier", "Murano", "Titan"] },
    { name: "Jeep", country: "United States", popularModels: ["Wrangler", "Grand Cherokee", "Cherokee", "Compass", "Gladiator", "Renegade", "Wagoneer"] },
    { name: "Hyundai", country: "United States", popularModels: ["Tucson", "Elantra", "Santa Fe", "Palisade", "Kona", "Sonata", "Ioniq 5", "Ioniq 6"] },
    { name: "Kia", country: "United States", popularModels: ["Sportage", "Seltos", "Sorento", "Telluride", "Forte", "Soul", "EV6", "EV9", "Carnival"] },
    { name: "Subaru", country: "United States", popularModels: ["Outback", "Forester", "Crosstrek", "Ascent", "Impreza", "Legacy", "WRX", "BRZ"] },
    { name: "Mazda", country: "United States", popularModels: ["CX-5", "CX-50", "Mazda3", "CX-9", "CX-30", "CX-90", "MX-5 Miata"] },
    { name: "Volkswagen", country: "United States", popularModels: ["Tiguan", "Jetta", "Atlas", "Taos", "ID.4", "Golf GTI"] },
    { name: "BMW", country: "United States", popularModels: ["X3", "X5", "3 Series", "5 Series", "X1", "4 Series", "X7", "iX"] },
    { name: "Mercedes-Benz", country: "United States", popularModels: ["GLE", "GLC", "C-Class", "E-Class", "GLA", "S-Class", "GLB", "EQS"] },
    { name: "Lexus", country: "United States", popularModels: ["RX", "NX", "ES", "GX", "UX", "IS", "LX", "LC"] },
    { name: "Dodge", country: "United States", popularModels: ["Charger", "Challenger", "Durango", "Hornet"] },
    { name: "Cadillac", country: "United States", popularModels: ["Escalade", "CT5", "XT4", "XT5", "XT6", "Lyriq"] },
    { name: "Lincoln", country: "United States", popularModels: ["Navigator", "Aviator", "Corsair", "Nautilus"] },
    { name: "Rivian", country: "United States", popularModels: ["R1T", "R1S"] },
    { name: "Lucid", country: "United States", popularModels: ["Air", "Gravity"] },
    { name: "Genesis", country: "United States", popularModels: ["G70", "G80", "GV70", "GV80", "G90", "GV60"] },
    { name: "Acura", country: "United States", popularModels: ["Integra", "TLX", "MDX", "RDX"] },
    { name: "Infiniti", country: "United States", popularModels: ["Q50", "QX50", "QX55", "QX60", "QX80"] },
    { name: "Volvo", country: "United States", popularModels: ["XC60", "XC90", "XC40", "S60", "S90", "C40"] },
    { name: "Porsche", country: "United States", popularModels: ["Cayenne", "Macan", "911", "Taycan", "Panamera"] },
    { name: "Land Rover", country: "United States", popularModels: ["Range Rover", "Range Rover Sport", "Defender", "Discovery", "Evoque"] },
    { name: "Audi", country: "United States", popularModels: ["Q5", "Q7", "A4", "A6", "Q3", "e-tron", "A3", "Q8"] },
  ],
  
  "Saudi Arabia": [
    { name: "Toyota", country: "Saudi Arabia", popularModels: ["Hilux", "Land Cruiser", "Camry", "Corolla", "RAV4", "Prado", "Fortuner", "Innova", "Yaris"] },
    { name: "Hyundai", country: "Saudi Arabia", popularModels: ["Elantra", "Tucson", "Santa Fe", "Accent", "Creta", "Kona", "Sonata", "Staria"] },
    { name: "Nissan", country: "Saudi Arabia", popularModels: ["Patrol", "Sunny", "X-Trail", "Altima", "Kicks", "Pathfinder", "Navara"] },
    { name: "Kia", country: "Saudi Arabia", popularModels: ["Sportage", "Cerato", "Sorento", "Picanto", "Seltos", "K5", "Carnival"] },
    { name: "Chevrolet", country: "Saudi Arabia", popularModels: ["Tahoe", "Suburban", "Silverado", "Traverse", "Equinox", "Blazer"] },
    { name: "Ford", country: "Saudi Arabia", popularModels: ["F-150", "Explorer", "Edge", "Ranger", "Expedition", "Bronco"] },
    { name: "GMC", country: "Saudi Arabia", popularModels: ["Sierra", "Yukon", "Terrain", "Acadia"] },
    { name: "Mercedes-Benz", country: "Saudi Arabia", popularModels: ["C-Class", "E-Class", "S-Class", "GLC", "GLE", "G-Class"] },
    { name: "BMW", country: "Saudi Arabia", popularModels: ["3 Series", "5 Series", "7 Series", "X5", "X3", "X7"] },
    { name: "Lexus", country: "Saudi Arabia", popularModels: ["ES", "RX", "LX", "NX", "GX", "IS"] },
    { name: "Geely", country: "Saudi Arabia", popularModels: ["Coolray", "Azkarra", "Emgrand", "Monjaro"] },
    { name: "Chery", country: "Saudi Arabia", popularModels: ["Tiggo 7 Pro", "Tiggo 8 Pro", "Arrizo 6"] },
    { name: "MG", country: "Saudi Arabia", popularModels: ["ZS", "HS", "RX5", "MG5"] },
    { name: "Jetour", country: "Saudi Arabia", popularModels: ["X70", "T2", "Dashing"] },
  ],
  
  "Egypt": [
    { name: "Hyundai", country: "Egypt", popularModels: ["Elantra", "Tucson", "Creta", "Accent", "Santa Fe", "i10", "Verna"] },
    { name: "Nissan", country: "Egypt", popularModels: ["Sunny", "Sentra", "X-Trail", "Kicks", "Patrol", "Qashqai"] },
    { name: "Toyota", country: "Egypt", popularModels: ["Corolla", "Camry", "RAV4", "Hilux", "Land Cruiser", "Yaris", "Fortuner", "Rush"] },
    { name: "Kia", country: "Egypt", popularModels: ["Cerato", "Sportage", "Rio", "Picanto", "Sorento", "Seltos"] },
    { name: "Chevrolet", country: "Egypt", popularModels: ["Optra", "Captiva", "Tahoe"] },
    { name: "Peugeot", country: "Egypt", popularModels: ["301", "308", "3008", "2008", "5008", "208"] },
    { name: "Renault", country: "Egypt", popularModels: ["Logan", "Duster", "Megane", "Captur", "Koleos"] },
    { name: "MG", country: "Egypt", popularModels: ["ZS", "HS", "RX5", "MG5"] },
    { name: "Chery", country: "Egypt", popularModels: ["Tiggo 7 Pro", "Tiggo 8 Pro", "Arrizo 6"] },
    { name: "BYD", country: "Egypt", popularModels: ["Atto 3", "Seal", "Dolphin", "Han"] },
    { name: "Fiat", country: "Egypt", popularModels: ["Tipo", "500", "Punto"] },
    { name: "Suzuki", country: "Egypt", popularModels: ["Swift", "Dzire", "Ertiga", "Baleno", "Ciaz"] },
  ],
  
  "Jordan": [
    { name: "Toyota", country: "Jordan", popularModels: ["Corolla", "Camry", "RAV4", "Hilux", "Land Cruiser", "Prado", "Yaris"] },
    { name: "Hyundai", country: "Jordan", popularModels: ["Elantra", "Tucson", "Santa Fe", "Accent", "Creta", "Kona"] },
    { name: "Kia", country: "Jordan", popularModels: ["Cerato", "Sportage", "Rio", "Sorento", "Picanto", "Seltos"] },
    { name: "Nissan", country: "Jordan", popularModels: ["Sunny", "X-Trail", "Patrol", "Kicks", "Altima"] },
    { name: "Mitsubishi", country: "Jordan", popularModels: ["Lancer", "Outlander", "Pajero", "ASX", "L200"] },
    { name: "Honda", country: "Jordan", popularModels: ["Civic", "Accord", "CR-V", "HR-V"] },
    { name: "Suzuki", country: "Jordan", popularModels: ["Swift", "Vitara", "Jimny", "Celerio"] },
  ],

  "United Kingdom": [
    { name: "Ford", country: "United Kingdom", popularModels: ["Fiesta", "Focus", "Puma", "Kuga", "Mustang Mach-E", "Ranger", "Transit"] },
    { name: "Volkswagen", country: "United Kingdom", popularModels: ["Golf", "Polo", "T-Roc", "Tiguan", "T-Cross", "ID.3", "ID.4", "Passat"] },
    { name: "Toyota", country: "United Kingdom", popularModels: ["Yaris", "Corolla", "C-HR", "RAV4", "Aygo X", "Hilux", "Prius"] },
    { name: "BMW", country: "United Kingdom", popularModels: ["1 Series", "3 Series", "X1", "X3", "X5", "5 Series", "iX"] },
    { name: "Mercedes-Benz", country: "United Kingdom", popularModels: ["A-Class", "C-Class", "E-Class", "GLA", "GLC", "EQA", "EQC"] },
    { name: "Audi", country: "United Kingdom", popularModels: ["A3", "A4", "Q3", "Q5", "A1", "e-tron", "Q7"] },
    { name: "Hyundai", country: "United Kingdom", popularModels: ["Tucson", "i10", "i20", "Kona", "Ioniq 5", "Bayon", "Santa Fe"] },
    { name: "Kia", country: "United Kingdom", popularModels: ["Sportage", "Niro", "Ceed", "Picanto", "EV6", "Stonic", "Sorento"] },
    { name: "Nissan", country: "United Kingdom", popularModels: ["Qashqai", "Juke", "Leaf", "X-Trail", "Micra"] },
    { name: "Vauxhall", country: "United Kingdom", popularModels: ["Corsa", "Mokka", "Astra", "Crossland", "Grandland"] },
    { name: "Peugeot", country: "United Kingdom", popularModels: ["208", "2008", "308", "3008", "5008", "508"] },
    { name: "Mini", country: "United Kingdom", popularModels: ["Cooper", "Countryman", "Clubman"] },
    { name: "Land Rover", country: "United Kingdom", popularModels: ["Defender", "Discovery Sport", "Range Rover Evoque", "Range Rover Sport", "Range Rover", "Discovery"] },
    { name: "Jaguar", country: "United Kingdom", popularModels: ["F-Pace", "E-Pace", "I-Pace", "XE", "XF"] },
    { name: "Tesla", country: "United Kingdom", popularModels: ["Model 3", "Model Y", "Model S", "Model X"] },
    { name: "Volvo", country: "United Kingdom", popularModels: ["XC40", "XC60", "XC90", "C40", "S60", "V60"] },
    { name: "Skoda", country: "United Kingdom", popularModels: ["Octavia", "Kodiaq", "Karoq", "Fabia", "Kamiq", "Enyaq"] },
    { name: "SEAT/Cupra", country: "United Kingdom", popularModels: ["Leon", "Ibiza", "Arona", "Ateca", "Formentor", "Born"] },
    { name: "Renault", country: "United Kingdom", popularModels: ["Clio", "Captur", "Arkana", "Megane E-Tech", "Zoe"] },
    { name: "Citroën", country: "United Kingdom", popularModels: ["C3", "C4", "C5 Aircross", "Berlingo"] },
    { name: "Dacia", country: "United Kingdom", popularModels: ["Sandero", "Duster", "Jogger", "Spring"] },
    { name: "MG", country: "United Kingdom", popularModels: ["ZS", "HS", "MG4", "MG5"] },
    { name: "BYD", country: "United Kingdom", popularModels: ["Atto 3", "Dolphin", "Seal"] },
  ],

  "Germany": [
    { name: "Volkswagen", country: "Germany", popularModels: ["Golf", "Tiguan", "Passat", "Polo", "T-Roc", "T-Cross", "ID.3", "ID.4", "ID.Buzz", "Arteon", "Touareg"] },
    { name: "BMW", country: "Germany", popularModels: ["3 Series", "1 Series", "X1", "X3", "X5", "5 Series", "2 Series", "4 Series", "iX", "i4"] },
    { name: "Mercedes-Benz", country: "Germany", popularModels: ["C-Class", "E-Class", "A-Class", "GLC", "GLE", "S-Class", "GLA", "CLA", "EQS", "EQE"] },
    { name: "Audi", country: "Germany", popularModels: ["A3", "A4", "A6", "Q3", "Q5", "Q7", "Q8", "e-tron", "A5", "Q2"] },
    { name: "Opel", country: "Germany", popularModels: ["Corsa", "Astra", "Mokka", "Crossland", "Grandland", "Insignia"] },
    { name: "Skoda", country: "Germany", popularModels: ["Octavia", "Kodiaq", "Karoq", "Kamiq", "Fabia", "Superb", "Enyaq"] },
    { name: "Toyota", country: "Germany", popularModels: ["Corolla", "Yaris", "RAV4", "C-HR", "Aygo X", "Prius"] },
    { name: "Hyundai", country: "Germany", popularModels: ["Tucson", "Kona", "i20", "i30", "Ioniq 5", "Ioniq 6", "Bayon"] },
    { name: "Kia", country: "Germany", popularModels: ["Sportage", "Ceed", "Niro", "EV6", "Stonic", "Picanto", "Sorento"] },
    { name: "Tesla", country: "Germany", popularModels: ["Model 3", "Model Y", "Model S", "Model X"] },
    { name: "Porsche", country: "Germany", popularModels: ["Cayenne", "Macan", "911", "Taycan", "Panamera"] },
    { name: "Ford", country: "Germany", popularModels: ["Focus", "Kuga", "Puma", "Fiesta", "Explorer", "Mustang Mach-E"] },
    { name: "SEAT/Cupra", country: "Germany", popularModels: ["Leon", "Ibiza", "Arona", "Ateca", "Formentor", "Born"] },
    { name: "Renault", country: "Germany", popularModels: ["Clio", "Captur", "Arkana", "Megane E-Tech"] },
    { name: "Fiat", country: "Germany", popularModels: ["500", "Panda", "Tipo", "500X"] },
    { name: "Volvo", country: "Germany", popularModels: ["XC40", "XC60", "XC90", "C40", "S60", "V60"] },
    { name: "Dacia", country: "Germany", popularModels: ["Sandero", "Duster", "Jogger", "Spring"] },
    { name: "Mini", country: "Germany", popularModels: ["Cooper", "Countryman", "Clubman"] },
    { name: "Peugeot", country: "Germany", popularModels: ["208", "2008", "308", "3008", "5008"] },
    { name: "Citroën", country: "Germany", popularModels: ["C3", "C4", "C5 Aircross"] },
  ],

  "France": [
    { name: "Peugeot", country: "France", popularModels: ["208", "2008", "308", "3008", "408", "5008", "508", "Rifter"] },
    { name: "Renault", country: "France", popularModels: ["Clio", "Captur", "Megane", "Arkana", "Austral", "Scenic", "Kangoo", "Trafic"] },
    { name: "Citroën", country: "France", popularModels: ["C3", "C4", "C5 Aircross", "C3 Aircross", "Berlingo", "C5 X"] },
    { name: "Dacia", country: "France", popularModels: ["Sandero", "Duster", "Jogger", "Spring", "Logan"] },
    { name: "Toyota", country: "France", popularModels: ["Yaris", "Yaris Cross", "Corolla", "C-HR", "RAV4", "Aygo X"] },
    { name: "Volkswagen", country: "France", popularModels: ["Golf", "Polo", "T-Roc", "Tiguan", "T-Cross", "ID.3", "ID.4"] },
    { name: "DS Automobiles", country: "France", popularModels: ["DS 3", "DS 4", "DS 7", "DS 9"] },
    { name: "Hyundai", country: "France", popularModels: ["Tucson", "Kona", "i10", "i20", "Ioniq 5", "Bayon"] },
    { name: "Kia", country: "France", popularModels: ["Sportage", "Niro", "Ceed", "Stonic", "EV6", "Picanto"] },
    { name: "BMW", country: "France", popularModels: ["1 Series", "3 Series", "X1", "X3", "X5"] },
    { name: "Mercedes-Benz", country: "France", popularModels: ["A-Class", "C-Class", "GLA", "GLC", "CLA"] },
    { name: "Audi", country: "France", popularModels: ["A3", "A4", "Q3", "Q5", "A1"] },
    { name: "Tesla", country: "France", popularModels: ["Model 3", "Model Y"] },
    { name: "Fiat", country: "France", popularModels: ["500", "Panda", "Tipo"] },
    { name: "Opel", country: "France", popularModels: ["Corsa", "Mokka", "Astra", "Crossland"] },
    { name: "Nissan", country: "France", popularModels: ["Qashqai", "Juke", "Leaf", "X-Trail", "Micra"] },
    { name: "Volvo", country: "France", popularModels: ["XC40", "XC60", "XC90", "C40"] },
    { name: "MG", country: "France", popularModels: ["ZS", "MG4", "HS"] },
  ],

  "India": [
    { name: "Maruti Suzuki", country: "India", popularModels: ["Swift", "Baleno", "Brezza", "Ertiga", "Wagon R", "Alto", "Dzire", "Grand Vitara", "Fronx", "Jimny", "Invicto", "Ciaz", "XL6"] },
    { name: "Hyundai", country: "India", popularModels: ["Creta", "Venue", "i20", "i10 Nios", "Verna", "Tucson", "Alcazar", "Exter", "Kona Electric"] },
    { name: "Tata", country: "India", popularModels: ["Nexon", "Punch", "Harrier", "Safari", "Altroz", "Tiago", "Tigor", "Nexon EV"] },
    { name: "Mahindra", country: "India", popularModels: ["XUV700", "Thar", "Scorpio-N", "XUV400", "Bolero", "XUV300", "Scorpio Classic"] },
    { name: "Kia", country: "India", popularModels: ["Seltos", "Sonet", "Carens", "EV6"] },
    { name: "Toyota", country: "India", popularModels: ["Innova Crysta", "Fortuner", "Urban Cruiser Hyryder", "Glanza", "Camry", "Hilux"] },
    { name: "Honda", country: "India", popularModels: ["City", "Amaze", "Elevate", "WR-V"] },
    { name: "MG", country: "India", popularModels: ["Hector", "Hector Plus", "Astor", "Gloster", "ZS EV", "Comet EV"] },
    { name: "Skoda", country: "India", popularModels: ["Kushaq", "Slavia", "Kodiaq", "Superb"] },
    { name: "Volkswagen", country: "India", popularModels: ["Taigun", "Virtus"] },
    { name: "Nissan", country: "India", popularModels: ["Magnite", "X-Trail", "Kicks"] },
    { name: "Renault", country: "India", popularModels: ["Kiger", "Kwid", "Triber"] },
    { name: "Citroën", country: "India", popularModels: ["C3", "C3 Aircross", "C5 Aircross"] },
    { name: "Jeep", country: "India", popularModels: ["Compass", "Meridian", "Grand Cherokee", "Wrangler"] },
    { name: "BMW", country: "India", popularModels: ["3 Series", "5 Series", "X1", "X3", "X5", "X7", "2 Series Gran Coupe"] },
    { name: "Mercedes-Benz", country: "India", popularModels: ["C-Class", "E-Class", "GLC", "GLE", "A-Class", "S-Class", "GLA", "GLS", "EQS"] },
    { name: "Audi", country: "India", popularModels: ["A4", "A6", "Q3", "Q5", "Q7", "e-tron"] },
    { name: "Volvo", country: "India", popularModels: ["XC40", "XC60", "XC90", "S60", "S90"] },
    { name: "BYD", country: "India", popularModels: ["Atto 3", "Seal", "e6"] },
  ],

  "Canada": [
    { name: "Ford", country: "Canada", popularModels: ["F-150", "Escape", "Explorer", "Ranger", "Bronco", "Mustang", "Edge", "Maverick"] },
    { name: "Toyota", country: "Canada", popularModels: ["RAV4", "Corolla", "Camry", "Highlander", "Tacoma", "4Runner", "Tundra", "Prius"] },
    { name: "Honda", country: "Canada", popularModels: ["CR-V", "Civic", "Accord", "HR-V", "Pilot"] },
    { name: "Chevrolet", country: "Canada", popularModels: ["Silverado", "Equinox", "Trax", "Traverse", "Tahoe", "Colorado"] },
    { name: "Ram", country: "Canada", popularModels: ["1500", "2500", "3500", "ProMaster"] },
    { name: "Hyundai", country: "Canada", popularModels: ["Tucson", "Elantra", "Kona", "Santa Fe", "Palisade", "Ioniq 5", "Venue"] },
    { name: "Kia", country: "Canada", popularModels: ["Sportage", "Seltos", "Forte", "Sorento", "Telluride", "Soul", "EV6", "Niro"] },
    { name: "Mazda", country: "Canada", popularModels: ["CX-5", "CX-50", "Mazda3", "CX-30", "CX-9", "CX-90"] },
    { name: "Nissan", country: "Canada", popularModels: ["Rogue", "Kicks", "Sentra", "Pathfinder", "Frontier", "Murano"] },
    { name: "Jeep", country: "Canada", popularModels: ["Wrangler", "Grand Cherokee", "Compass", "Gladiator"] },
    { name: "GMC", country: "Canada", popularModels: ["Sierra", "Terrain", "Acadia", "Yukon", "Canyon"] },
    { name: "Subaru", country: "Canada", popularModels: ["Outback", "Forester", "Crosstrek", "Impreza", "Ascent"] },
    { name: "Volkswagen", country: "Canada", popularModels: ["Tiguan", "Jetta", "Atlas", "Taos", "ID.4", "Golf GTI"] },
    { name: "Tesla", country: "Canada", popularModels: ["Model Y", "Model 3", "Model S", "Model X"] },
    { name: "BMW", country: "Canada", popularModels: ["X3", "X5", "3 Series", "5 Series", "X1"] },
    { name: "Mercedes-Benz", country: "Canada", popularModels: ["GLC", "GLE", "C-Class", "E-Class", "GLA"] },
    { name: "Audi", country: "Canada", popularModels: ["Q5", "Q7", "A4", "A3", "Q3", "e-tron"] },
    { name: "Dodge", country: "Canada", popularModels: ["Charger", "Durango", "Challenger"] },
  ],

  "Australia": [
    { name: "Toyota", country: "Australia", popularModels: ["HiLux", "RAV4", "Corolla", "LandCruiser", "Kluger", "Camry", "Prado", "Yaris Cross", "C-HR", "Fortuner"] },
    { name: "Ford", country: "Australia", popularModels: ["Ranger", "Everest", "Puma", "Mustang", "Escape", "Bronco"] },
    { name: "Mazda", country: "Australia", popularModels: ["CX-5", "CX-3", "Mazda3", "CX-30", "CX-8", "CX-9", "CX-60", "BT-50"] },
    { name: "Hyundai", country: "Australia", popularModels: ["Tucson", "i30", "Kona", "Santa Fe", "Venue", "Staria", "Ioniq 5"] },
    { name: "Kia", country: "Australia", popularModels: ["Sportage", "Cerato", "Seltos", "Sorento", "Carnival", "Stonic", "EV6", "Niro"] },
    { name: "Mitsubishi", country: "Australia", popularModels: ["Outlander", "ASX", "Triton", "Pajero Sport", "Eclipse Cross"] },
    { name: "Isuzu", country: "Australia", popularModels: ["D-Max", "MU-X"] },
    { name: "Nissan", country: "Australia", popularModels: ["X-Trail", "Navara", "Qashqai", "Patrol", "Juke", "Leaf"] },
    { name: "Subaru", country: "Australia", popularModels: ["Outback", "Forester", "XV/Crosstrek", "Impreza", "BRZ", "WRX"] },
    { name: "Volkswagen", country: "Australia", popularModels: ["Tiguan", "T-Roc", "T-Cross", "Golf", "Amarok", "Polo", "ID.4"] },
    { name: "Tesla", country: "Australia", popularModels: ["Model 3", "Model Y", "Model S", "Model X"] },
    { name: "MG", country: "Australia", popularModels: ["ZS", "HS", "MG4", "MG3"] },
    { name: "BMW", country: "Australia", popularModels: ["X3", "X5", "3 Series", "1 Series", "X1", "5 Series"] },
    { name: "Mercedes-Benz", country: "Australia", popularModels: ["C-Class", "GLC", "GLA", "A-Class", "GLE"] },
    { name: "Suzuki", country: "Australia", popularModels: ["Swift", "Vitara", "Jimny", "Baleno", "S-Cross", "Ignis"] },
    { name: "Honda", country: "Australia", popularModels: ["CR-V", "Civic", "HR-V", "Jazz", "Accord"] },
    { name: "GWM/Haval", country: "Australia", popularModels: ["Jolion", "H6", "Ute Cannon"] },
    { name: "BYD", country: "Australia", popularModels: ["Atto 3", "Dolphin", "Seal"] },
    { name: "Land Rover", country: "Australia", popularModels: ["Defender", "Discovery", "Range Rover Sport", "Range Rover Evoque"] },
    { name: "Lexus", country: "Australia", popularModels: ["NX", "RX", "UX", "IS", "LX"] },
  ],

  "Japan": [
    { name: "Toyota", country: "Japan", popularModels: ["Yaris", "Corolla", "Prius", "RAV4", "Harrier", "Land Cruiser", "Alphard", "Vellfire", "Noah", "Voxy", "Aqua", "Raize", "Crown", "Camry", "Hilux", "GR86", "Sienta"] },
    { name: "Honda", country: "Japan", popularModels: ["N-Box", "Fit", "Vezel/HR-V", "Freed", "Step Wagon", "Civic", "CR-V", "N-WGN", "N-ONE"] },
    { name: "Nissan", country: "Japan", popularModels: ["Note", "Serena", "X-Trail", "Kicks", "Sakura", "Ariya", "Leaf", "Dayz", "Fairlady Z"] },
    { name: "Suzuki", country: "Japan", popularModels: ["Spacia", "Hustler", "Swift", "Jimny", "Alto", "Wagon R", "Solio", "Xbee", "Every"] },
    { name: "Daihatsu", country: "Japan", popularModels: ["Tanto", "Move", "Rocky", "Taft", "Mira", "Cast", "Hijet"] },
    { name: "Mazda", country: "Japan", popularModels: ["Mazda3", "CX-5", "CX-30", "CX-60", "CX-8", "Mazda2", "MX-5", "Mazda6"] },
    { name: "Subaru", country: "Japan", popularModels: ["Forester", "Outback", "Levorg", "Impreza", "Crosstrek", "WRX", "BRZ"] },
    { name: "Mitsubishi", country: "Japan", popularModels: ["Outlander", "Delica D:5", "Eclipse Cross", "eK Wagon", "eK Cross", "RVR"] },
    { name: "Lexus", country: "Japan", popularModels: ["NX", "RX", "UX", "IS", "ES", "LX", "LC", "RZ"] },
  ],

  "South Korea": [
    { name: "Hyundai", country: "South Korea", popularModels: ["Grandeur/Azera", "Sonata", "Avante/Elantra", "Tucson", "Santa Fe", "Palisade", "Kona", "Casper", "Ioniq 5", "Ioniq 6", "Staria"] },
    { name: "Kia", country: "South Korea", popularModels: ["Sorento", "Sportage", "K5", "K8", "Carnival", "Ray", "Morning/Picanto", "Niro", "EV6", "EV9", "Seltos"] },
    { name: "Genesis", country: "South Korea", popularModels: ["G80", "G70", "G90", "GV70", "GV80", "GV60", "Electrified G80"] },
    { name: "Renault Korea (Samsung)", country: "South Korea", popularModels: ["QM6", "XM3", "SM6"] },
    { name: "Chevrolet", country: "South Korea", popularModels: ["Trailblazer", "Equinox", "Tahoe", "Bolt EV"] },
    { name: "Tesla", country: "South Korea", popularModels: ["Model 3", "Model Y"] },
    { name: "BMW", country: "South Korea", popularModels: ["5 Series", "3 Series", "X5", "X3", "iX", "i4"] },
    { name: "Mercedes-Benz", country: "South Korea", popularModels: ["E-Class", "S-Class", "GLC", "GLE", "C-Class"] },
  ],

  "China": [
    { name: "BYD", country: "China", popularModels: ["Song Plus", "Qin Plus", "Yuan Plus", "Han", "Tang", "Seal", "Dolphin", "Atto 3", "Seagull"] },
    { name: "Tesla", country: "China", popularModels: ["Model Y", "Model 3", "Model S", "Model X"] },
    { name: "Volkswagen", country: "China", popularModels: ["Lavida", "Sagitar", "Bora", "Tiguan L", "Tayron", "Magotan", "ID.4", "ID.6"] },
    { name: "Toyota", country: "China", popularModels: ["Camry", "Corolla", "RAV4", "Highlander", "Levin", "Crown", "bZ4X"] },
    { name: "Honda", country: "China", popularModels: ["CR-V", "Civic", "Accord", "Vezel", "Breeze", "e:NS1"] },
    { name: "NIO", country: "China", popularModels: ["ES8", "ES6", "EC6", "ET7", "ET5", "EC7"] },
    { name: "XPeng", country: "China", popularModels: ["P7", "G9", "G6", "P5", "G3"] },
    { name: "Li Auto", country: "China", popularModels: ["L9", "L8", "L7", "L6", "Mega"] },
    { name: "Geely", country: "China", popularModels: ["Emgrand", "Coolray", "Xingyue L", "Boyue", "Preface"] },
    { name: "Chery", country: "China", popularModels: ["Tiggo 7 Pro", "Tiggo 8 Pro", "Arrizo 6", "Arrizo 8"] },
    { name: "Changan", country: "China", popularModels: ["CS75 Plus", "CS55 Plus", "CS35 Plus", "Uni-T", "Uni-K", "Uni-V", "Eado Plus"] },
    { name: "GWM/Haval", country: "China", popularModels: ["H6", "Jolion", "Dargo", "Tank 300", "Tank 500"] },
    { name: "GAC", country: "China", popularModels: ["GS4", "GS8", "Aion S", "Aion Y", "Emkoo"] },
    { name: "BAIC", country: "China", popularModels: ["X55", "X35", "BJ40", "EU5"] },
    { name: "BMW", country: "China", popularModels: ["3 Series", "5 Series", "X3", "X5", "iX3"] },
    { name: "Mercedes-Benz", country: "China", popularModels: ["C-Class", "E-Class", "GLC", "GLE", "S-Class", "A-Class"] },
    { name: "Audi", country: "China", popularModels: ["A4L", "A6L", "Q5L", "Q3", "A3"] },
  ],
};

export function getAllCountries(): string[] {
  return Object.keys(carMakersByCountry);
}

export function getCarMakersByCountry(country: string): CarMakerData[] {
  const countryMakers = carMakersByCountry[country];
  if (countryMakers && countryMakers.length > 0) {
    return countryMakers;
  }
  return globalMakers;
}

export function getAllCarMakers(): string[] {
  const makers = new Set<string>();
  globalMakers.forEach(maker => makers.add(maker.name));
  Object.values(carMakersByCountry).forEach(countryMakers => {
    countryMakers.forEach(maker => makers.add(maker.name));
  });
  return Array.from(makers).sort();
}

export function getGlobalMakers(): CarMakerData[] {
  return globalMakers;
}
