// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/reservations-calendar/TimelineCalendar.tsx": () => import("../components/mockups/reservations-calendar/TimelineCalendar.tsx"),
  "./components/mockups/contract-workspace/ContractWorkspace.tsx": () => import("../components/mockups/contract-workspace/ContractWorkspace.tsx")
};
