export interface CountryData {
  code: string;
  name: string;
  currency?: string;
  currencyCode?: string;
  vatRate?: number;
  currencySymbol?: string;
  phoneCode?: string;
  phoneDigits?: number;
}

export const COUNTRY_PHONE_DATA: Record<string, { phoneCode: string; phoneDigits: number; format?: string }> = {
  AF: { phoneCode: "+93", phoneDigits: 9 },
  AL: { phoneCode: "+355", phoneDigits: 9 },
  DZ: { phoneCode: "+213", phoneDigits: 9 },
  AD: { phoneCode: "+376", phoneDigits: 6 },
  AO: { phoneCode: "+244", phoneDigits: 9 },
  AG: { phoneCode: "+1", phoneDigits: 10 },
  AR: { phoneCode: "+54", phoneDigits: 10 },
  AM: { phoneCode: "+374", phoneDigits: 8 },
  AU: { phoneCode: "+61", phoneDigits: 9 },
  AT: { phoneCode: "+43", phoneDigits: 10 },
  AZ: { phoneCode: "+994", phoneDigits: 9 },
  BS: { phoneCode: "+1", phoneDigits: 10 },
  BH: { phoneCode: "+973", phoneDigits: 8 },
  BD: { phoneCode: "+880", phoneDigits: 10 },
  BB: { phoneCode: "+1", phoneDigits: 10 },
  BY: { phoneCode: "+375", phoneDigits: 10 },
  BE: { phoneCode: "+32", phoneDigits: 9 },
  BZ: { phoneCode: "+501", phoneDigits: 7 },
  BJ: { phoneCode: "+229", phoneDigits: 8 },
  BT: { phoneCode: "+975", phoneDigits: 8 },
  BO: { phoneCode: "+591", phoneDigits: 8 },
  BA: { phoneCode: "+387", phoneDigits: 8 },
  BW: { phoneCode: "+267", phoneDigits: 8 },
  BR: { phoneCode: "+55", phoneDigits: 11 },
  BN: { phoneCode: "+673", phoneDigits: 7 },
  BG: { phoneCode: "+359", phoneDigits: 9 },
  BF: { phoneCode: "+226", phoneDigits: 8 },
  BI: { phoneCode: "+257", phoneDigits: 8 },
  KH: { phoneCode: "+855", phoneDigits: 9 },
  CM: { phoneCode: "+237", phoneDigits: 9 },
  CA: { phoneCode: "+1", phoneDigits: 10 },
  CV: { phoneCode: "+238", phoneDigits: 7 },
  CF: { phoneCode: "+236", phoneDigits: 8 },
  TD: { phoneCode: "+235", phoneDigits: 8 },
  CL: { phoneCode: "+56", phoneDigits: 9 },
  CN: { phoneCode: "+86", phoneDigits: 11 },
  CO: { phoneCode: "+57", phoneDigits: 10 },
  KM: { phoneCode: "+269", phoneDigits: 7 },
  CG: { phoneCode: "+242", phoneDigits: 9 },
  CD: { phoneCode: "+243", phoneDigits: 9 },
  CR: { phoneCode: "+506", phoneDigits: 8 },
  HR: { phoneCode: "+385", phoneDigits: 9 },
  CU: { phoneCode: "+53", phoneDigits: 8 },
  CY: { phoneCode: "+357", phoneDigits: 8 },
  CZ: { phoneCode: "+420", phoneDigits: 9 },
  CI: { phoneCode: "+225", phoneDigits: 10 },
  DK: { phoneCode: "+45", phoneDigits: 8 },
  DJ: { phoneCode: "+253", phoneDigits: 8 },
  DM: { phoneCode: "+1", phoneDigits: 10 },
  DO: { phoneCode: "+1", phoneDigits: 10 },
  EC: { phoneCode: "+593", phoneDigits: 9 },
  EG: { phoneCode: "+20", phoneDigits: 10 },
  SV: { phoneCode: "+503", phoneDigits: 8 },
  GQ: { phoneCode: "+240", phoneDigits: 9 },
  ER: { phoneCode: "+291", phoneDigits: 7 },
  EE: { phoneCode: "+372", phoneDigits: 8 },
  SZ: { phoneCode: "+268", phoneDigits: 8 },
  ET: { phoneCode: "+251", phoneDigits: 9 },
  FJ: { phoneCode: "+679", phoneDigits: 7 },
  FI: { phoneCode: "+358", phoneDigits: 10 },
  FR: { phoneCode: "+33", phoneDigits: 9 },
  GA: { phoneCode: "+241", phoneDigits: 7 },
  GM: { phoneCode: "+220", phoneDigits: 7 },
  GE: { phoneCode: "+995", phoneDigits: 9 },
  DE: { phoneCode: "+49", phoneDigits: 11 },
  GH: { phoneCode: "+233", phoneDigits: 9 },
  GR: { phoneCode: "+30", phoneDigits: 10 },
  GD: { phoneCode: "+1", phoneDigits: 10 },
  GT: { phoneCode: "+502", phoneDigits: 8 },
  GN: { phoneCode: "+224", phoneDigits: 9 },
  GW: { phoneCode: "+245", phoneDigits: 7 },
  GY: { phoneCode: "+592", phoneDigits: 7 },
  HT: { phoneCode: "+509", phoneDigits: 8 },
  HN: { phoneCode: "+504", phoneDigits: 8 },
  HK: { phoneCode: "+852", phoneDigits: 8 },
  HU: { phoneCode: "+36", phoneDigits: 9 },
  IS: { phoneCode: "+354", phoneDigits: 7 },
  IN: { phoneCode: "+91", phoneDigits: 10 },
  ID: { phoneCode: "+62", phoneDigits: 12 },
  IR: { phoneCode: "+98", phoneDigits: 10 },
  IQ: { phoneCode: "+964", phoneDigits: 10 },
  IE: { phoneCode: "+353", phoneDigits: 9 },
  IL: { phoneCode: "+972", phoneDigits: 9 },
  IT: { phoneCode: "+39", phoneDigits: 10 },
  JM: { phoneCode: "+1", phoneDigits: 10 },
  JP: { phoneCode: "+81", phoneDigits: 10 },
  JO: { phoneCode: "+962", phoneDigits: 9 },
  KZ: { phoneCode: "+7", phoneDigits: 10 },
  KE: { phoneCode: "+254", phoneDigits: 10 },
  KI: { phoneCode: "+686", phoneDigits: 5 },
  KP: { phoneCode: "+850", phoneDigits: 10 },
  KR: { phoneCode: "+82", phoneDigits: 10 },
  KW: { phoneCode: "+965", phoneDigits: 8 },
  KG: { phoneCode: "+996", phoneDigits: 9 },
  LA: { phoneCode: "+856", phoneDigits: 10 },
  LV: { phoneCode: "+371", phoneDigits: 8 },
  LB: { phoneCode: "+961", phoneDigits: 8 },
  LS: { phoneCode: "+266", phoneDigits: 8 },
  LR: { phoneCode: "+231", phoneDigits: 7 },
  LY: { phoneCode: "+218", phoneDigits: 10 },
  LI: { phoneCode: "+423", phoneDigits: 7 },
  LT: { phoneCode: "+370", phoneDigits: 8 },
  LU: { phoneCode: "+352", phoneDigits: 9 },
  MO: { phoneCode: "+853", phoneDigits: 8 },
  MG: { phoneCode: "+261", phoneDigits: 9 },
  MW: { phoneCode: "+265", phoneDigits: 9 },
  MY: { phoneCode: "+60", phoneDigits: 10 },
  MV: { phoneCode: "+960", phoneDigits: 7 },
  ML: { phoneCode: "+223", phoneDigits: 8 },
  MT: { phoneCode: "+356", phoneDigits: 8 },
  MR: { phoneCode: "+222", phoneDigits: 8 },
  MU: { phoneCode: "+230", phoneDigits: 8 },
  MX: { phoneCode: "+52", phoneDigits: 10 },
  MD: { phoneCode: "+373", phoneDigits: 8 },
  MC: { phoneCode: "+377", phoneDigits: 8 },
  MN: { phoneCode: "+976", phoneDigits: 8 },
  ME: { phoneCode: "+382", phoneDigits: 8 },
  MA: { phoneCode: "+212", phoneDigits: 9 },
  MZ: { phoneCode: "+258", phoneDigits: 9 },
  MM: { phoneCode: "+95", phoneDigits: 10 },
  NA: { phoneCode: "+264", phoneDigits: 10 },
  NR: { phoneCode: "+674", phoneDigits: 7 },
  NP: { phoneCode: "+977", phoneDigits: 10 },
  NL: { phoneCode: "+31", phoneDigits: 9 },
  NZ: { phoneCode: "+64", phoneDigits: 9 },
  NI: { phoneCode: "+505", phoneDigits: 8 },
  NE: { phoneCode: "+227", phoneDigits: 8 },
  NG: { phoneCode: "+234", phoneDigits: 10 },
  MK: { phoneCode: "+389", phoneDigits: 8 },
  NO: { phoneCode: "+47", phoneDigits: 8 },
  OM: { phoneCode: "+968", phoneDigits: 8 },
  PK: { phoneCode: "+92", phoneDigits: 10 },
  PA: { phoneCode: "+507", phoneDigits: 8 },
  PG: { phoneCode: "+675", phoneDigits: 8 },
  PY: { phoneCode: "+595", phoneDigits: 9 },
  PE: { phoneCode: "+51", phoneDigits: 9 },
  PH: { phoneCode: "+63", phoneDigits: 10 },
  PL: { phoneCode: "+48", phoneDigits: 9 },
  PT: { phoneCode: "+351", phoneDigits: 9 },
  PR: { phoneCode: "+1", phoneDigits: 10 },
  QA: { phoneCode: "+974", phoneDigits: 8 },
  RO: { phoneCode: "+40", phoneDigits: 10 },
  RU: { phoneCode: "+7", phoneDigits: 10 },
  RW: { phoneCode: "+250", phoneDigits: 9 },
  SA: { phoneCode: "+966", phoneDigits: 9 },
  SN: { phoneCode: "+221", phoneDigits: 9 },
  RS: { phoneCode: "+381", phoneDigits: 9 },
  SC: { phoneCode: "+248", phoneDigits: 7 },
  SL: { phoneCode: "+232", phoneDigits: 8 },
  SG: { phoneCode: "+65", phoneDigits: 8 },
  SK: { phoneCode: "+421", phoneDigits: 9 },
  SI: { phoneCode: "+386", phoneDigits: 8 },
  SB: { phoneCode: "+677", phoneDigits: 7 },
  SO: { phoneCode: "+252", phoneDigits: 8 },
  ZA: { phoneCode: "+27", phoneDigits: 9 },
  SS: { phoneCode: "+211", phoneDigits: 9 },
  ES: { phoneCode: "+34", phoneDigits: 9 },
  LK: { phoneCode: "+94", phoneDigits: 9 },
  SD: { phoneCode: "+249", phoneDigits: 9 },
  SR: { phoneCode: "+597", phoneDigits: 7 },
  SE: { phoneCode: "+46", phoneDigits: 10 },
  CH: { phoneCode: "+41", phoneDigits: 9 },
  SY: { phoneCode: "+963", phoneDigits: 9 },
  TW: { phoneCode: "+886", phoneDigits: 9 },
  TJ: { phoneCode: "+992", phoneDigits: 9 },
  TZ: { phoneCode: "+255", phoneDigits: 9 },
  TH: { phoneCode: "+66", phoneDigits: 9 },
  TL: { phoneCode: "+670", phoneDigits: 8 },
  TG: { phoneCode: "+228", phoneDigits: 8 },
  TO: { phoneCode: "+676", phoneDigits: 5 },
  TT: { phoneCode: "+1", phoneDigits: 10 },
  TN: { phoneCode: "+216", phoneDigits: 8 },
  TR: { phoneCode: "+90", phoneDigits: 10 },
  TM: { phoneCode: "+993", phoneDigits: 8 },
  TV: { phoneCode: "+688", phoneDigits: 5 },
  UG: { phoneCode: "+256", phoneDigits: 9 },
  UA: { phoneCode: "+380", phoneDigits: 9 },
  AE: { phoneCode: "+971", phoneDigits: 9 },
  GB: { phoneCode: "+44", phoneDigits: 10 },
  US: { phoneCode: "+1", phoneDigits: 10 },
  UY: { phoneCode: "+598", phoneDigits: 8 },
  UZ: { phoneCode: "+998", phoneDigits: 9 },
  VU: { phoneCode: "+678", phoneDigits: 7 },
  VE: { phoneCode: "+58", phoneDigits: 10 },
  VN: { phoneCode: "+84", phoneDigits: 10 },
  YE: { phoneCode: "+967", phoneDigits: 9 },
  ZM: { phoneCode: "+260", phoneDigits: 9 },
  ZW: { phoneCode: "+263", phoneDigits: 9 },
};

export const countries: CountryData[] = [
  { code: 'AF', name: 'Afghanistan' },
  { code: 'AX', name: 'Åland Islands' },
  { code: 'AL', name: 'Albania' },
  { code: 'DZ', name: 'Algeria' },
  { code: 'AS', name: 'American Samoa' },
  { code: 'AD', name: 'Andorra' },
  { code: 'AO', name: 'Angola' },
  { code: 'AI', name: 'Anguilla' },
  { code: 'AQ', name: 'Antarctica' },
  { code: 'AG', name: 'Antigua and Barbuda' },
  { code: 'AR', name: 'Argentina' },
  { code: 'AM', name: 'Armenia' },
  { code: 'AW', name: 'Aruba' },
  { code: 'AU', name: 'Australia' },
  { code: 'AT', name: 'Austria' },
  { code: 'AZ', name: 'Azerbaijan' },
  { code: 'BS', name: 'Bahamas' },
  { code: 'BH', name: 'Bahrain' },
  { code: 'BD', name: 'Bangladesh' },
  { code: 'BB', name: 'Barbados' },
  { code: 'BY', name: 'Belarus' },
  { code: 'BE', name: 'Belgium' },
  { code: 'BZ', name: 'Belize' },
  { code: 'BJ', name: 'Benin' },
  { code: 'BM', name: 'Bermuda' },
  { code: 'BT', name: 'Bhutan' },
  { code: 'BO', name: 'Bolivia' },
  { code: 'BQ', name: 'Bonaire, Sint Eustatius and Saba' },
  { code: 'BA', name: 'Bosnia and Herzegovina' },
  { code: 'BW', name: 'Botswana' },
  { code: 'BV', name: 'Bouvet Island' },
  { code: 'BR', name: 'Brazil' },
  { code: 'IO', name: 'British Indian Ocean Territory' },
  { code: 'BN', name: 'Brunei Darussalam' },
  { code: 'BG', name: 'Bulgaria' },
  { code: 'BF', name: 'Burkina Faso' },
  { code: 'BI', name: 'Burundi' },
  { code: 'CV', name: 'Cabo Verde' },
  { code: 'KH', name: 'Cambodia' },
  { code: 'CM', name: 'Cameroon' },
  { code: 'CA', name: 'Canada' },
  { code: 'KY', name: 'Cayman Islands' },
  { code: 'CF', name: 'Central African Republic' },
  { code: 'TD', name: 'Chad' },
  { code: 'CL', name: 'Chile' },
  { code: 'CN', name: 'China' },
  { code: 'CX', name: 'Christmas Island' },
  { code: 'CC', name: 'Cocos (Keeling) Islands' },
  { code: 'CO', name: 'Colombia' },
  { code: 'KM', name: 'Comoros' },
  { code: 'CD', name: 'Congo, Democratic Republic of the' },
  { code: 'CG', name: 'Congo' },
  { code: 'CK', name: 'Cook Islands' },
  { code: 'CR', name: 'Costa Rica' },
  { code: 'HR', name: 'Croatia' },
  { code: 'CU', name: 'Cuba' },
  { code: 'CW', name: 'Curaçao' },
  { code: 'CY', name: 'Cyprus' },
  { code: 'CZ', name: 'Czechia' },
  { code: 'CI', name: 'Côte d\'Ivoire' },
  { code: 'DK', name: 'Denmark' },
  { code: 'DJ', name: 'Djibouti' },
  { code: 'DM', name: 'Dominica' },
  { code: 'DO', name: 'Dominican Republic' },
  { code: 'EC', name: 'Ecuador' },
  { code: 'EG', name: 'Egypt' },
  { code: 'SV', name: 'El Salvador' },
  { code: 'GQ', name: 'Equatorial Guinea' },
  { code: 'ER', name: 'Eritrea' },
  { code: 'EE', name: 'Estonia' },
  { code: 'SZ', name: 'Eswatini' },
  { code: 'ET', name: 'Ethiopia' },
  { code: 'FK', name: 'Falkland Islands (Malvinas)' },
  { code: 'FO', name: 'Faroe Islands' },
  { code: 'FJ', name: 'Fiji' },
  { code: 'FI', name: 'Finland' },
  { code: 'FR', name: 'France' },
  { code: 'GF', name: 'French Guiana' },
  { code: 'PF', name: 'French Polynesia' },
  { code: 'TF', name: 'French Southern Territories' },
  { code: 'GA', name: 'Gabon' },
  { code: 'GM', name: 'Gambia' },
  { code: 'GE', name: 'Georgia' },
  { code: 'DE', name: 'Germany' },
  { code: 'GH', name: 'Ghana' },
  { code: 'GI', name: 'Gibraltar' },
  { code: 'GR', name: 'Greece' },
  { code: 'GL', name: 'Greenland' },
  { code: 'GD', name: 'Grenada' },
  { code: 'GP', name: 'Guadeloupe' },
  { code: 'GU', name: 'Guam' },
  { code: 'GT', name: 'Guatemala' },
  { code: 'GG', name: 'Guernsey' },
  { code: 'GN', name: 'Guinea' },
  { code: 'GW', name: 'Guinea-Bissau' },
  { code: 'GY', name: 'Guyana' },
  { code: 'HT', name: 'Haiti' },
  { code: 'HM', name: 'Heard Island and McDonald Islands' },
  { code: 'VA', name: 'Holy See' },
  { code: 'HN', name: 'Honduras' },
  { code: 'HK', name: 'Hong Kong' },
  { code: 'HU', name: 'Hungary' },
  { code: 'IS', name: 'Iceland' },
  { code: 'IN', name: 'India' },
  { code: 'ID', name: 'Indonesia' },
  { code: 'IR', name: 'Iran' },
  { code: 'IQ', name: 'Iraq' },
  { code: 'IE', name: 'Ireland' },
  { code: 'IM', name: 'Isle of Man' },
  { code: 'IL', name: 'Israel' },
  { code: 'IT', name: 'Italy' },
  { code: 'JM', name: 'Jamaica' },
  { code: 'JP', name: 'Japan' },
  { code: 'JE', name: 'Jersey' },
  { code: 'JO', name: 'Jordan' },
  { code: 'KZ', name: 'Kazakhstan' },
  { code: 'KE', name: 'Kenya' },
  { code: 'KI', name: 'Kiribati' },
  { code: 'KP', name: 'Korea, Democratic People\'s Republic of' },
  { code: 'KR', name: 'Korea, Republic of' },
  { code: 'KW', name: 'Kuwait' },
  { code: 'KG', name: 'Kyrgyzstan' },
  { code: 'LA', name: 'Lao People\'s Democratic Republic' },
  { code: 'LV', name: 'Latvia' },
  { code: 'LB', name: 'Lebanon' },
  { code: 'LS', name: 'Lesotho' },
  { code: 'LR', name: 'Liberia' },
  { code: 'LY', name: 'Libya' },
  { code: 'LI', name: 'Liechtenstein' },
  { code: 'LT', name: 'Lithuania' },
  { code: 'LU', name: 'Luxembourg' },
  { code: 'MO', name: 'Macao' },
  { code: 'MG', name: 'Madagascar' },
  { code: 'MW', name: 'Malawi' },
  { code: 'MY', name: 'Malaysia' },
  { code: 'MV', name: 'Maldives' },
  { code: 'ML', name: 'Mali' },
  { code: 'MT', name: 'Malta' },
  { code: 'MH', name: 'Marshall Islands' },
  { code: 'MQ', name: 'Martinique' },
  { code: 'MR', name: 'Mauritania' },
  { code: 'MU', name: 'Mauritius' },
  { code: 'YT', name: 'Mayotte' },
  { code: 'MX', name: 'Mexico' },
  { code: 'FM', name: 'Micronesia, Federated States of' },
  { code: 'MD', name: 'Moldova' },
  { code: 'MC', name: 'Monaco' },
  { code: 'MN', name: 'Mongolia' },
  { code: 'ME', name: 'Montenegro' },
  { code: 'MS', name: 'Montserrat' },
  { code: 'MA', name: 'Morocco' },
  { code: 'MZ', name: 'Mozambique' },
  { code: 'MM', name: 'Myanmar' },
  { code: 'NA', name: 'Namibia' },
  { code: 'NR', name: 'Nauru' },
  { code: 'NP', name: 'Nepal' },
  { code: 'NL', name: 'Netherlands' },
  { code: 'NC', name: 'New Caledonia' },
  { code: 'NZ', name: 'New Zealand' },
  { code: 'NI', name: 'Nicaragua' },
  { code: 'NE', name: 'Niger' },
  { code: 'NG', name: 'Nigeria' },
  { code: 'NU', name: 'Niue' },
  { code: 'NF', name: 'Norfolk Island' },
  { code: 'MK', name: 'North Macedonia' },
  { code: 'MP', name: 'Northern Mariana Islands' },
  { code: 'NO', name: 'Norway' },
  { code: 'OM', name: 'Oman' },
  { code: 'PK', name: 'Pakistan' },
  { code: 'PW', name: 'Palau' },
  { code: 'PS', name: 'Palestine, State of' },
  { code: 'PA', name: 'Panama' },
  { code: 'PG', name: 'Papua New Guinea' },
  { code: 'PY', name: 'Paraguay' },
  { code: 'PE', name: 'Peru' },
  { code: 'PH', name: 'Philippines' },
  { code: 'PN', name: 'Pitcairn' },
  { code: 'PL', name: 'Poland' },
  { code: 'PT', name: 'Portugal' },
  { code: 'PR', name: 'Puerto Rico' },
  { code: 'QA', name: 'Qatar' },
  { code: 'RO', name: 'Romania' },
  { code: 'RU', name: 'Russian Federation' },
  { code: 'RW', name: 'Rwanda' },
  { code: 'RE', name: 'Réunion' },
  { code: 'BL', name: 'Saint Barthélemy' },
  { code: 'SH', name: 'Saint Helena, Ascension and Tristan da Cunha' },
  { code: 'KN', name: 'Saint Kitts and Nevis' },
  { code: 'LC', name: 'Saint Lucia' },
  { code: 'MF', name: 'Saint Martin (French part)' },
  { code: 'PM', name: 'Saint Pierre and Miquelon' },
  { code: 'VC', name: 'Saint Vincent and the Grenadines' },
  { code: 'WS', name: 'Samoa' },
  { code: 'SM', name: 'San Marino' },
  { code: 'ST', name: 'Sao Tome and Principe' },
  { code: 'SA', name: 'Saudi Arabia' },
  { code: 'SN', name: 'Senegal' },
  { code: 'RS', name: 'Serbia' },
  { code: 'SC', name: 'Seychelles' },
  { code: 'SL', name: 'Sierra Leone' },
  { code: 'SG', name: 'Singapore' },
  { code: 'SX', name: 'Sint Maarten (Dutch part)' },
  { code: 'SK', name: 'Slovakia' },
  { code: 'SI', name: 'Slovenia' },
  { code: 'SB', name: 'Solomon Islands' },
  { code: 'SO', name: 'Somalia' },
  { code: 'ZA', name: 'South Africa' },
  { code: 'GS', name: 'South Georgia and the South Sandwich Islands' },
  { code: 'SS', name: 'South Sudan' },
  { code: 'ES', name: 'Spain' },
  { code: 'LK', name: 'Sri Lanka' },
  { code: 'SD', name: 'Sudan' },
  { code: 'SR', name: 'Suriname' },
  { code: 'SJ', name: 'Svalbard and Jan Mayen' },
  { code: 'SE', name: 'Sweden' },
  { code: 'CH', name: 'Switzerland' },
  { code: 'SY', name: 'Syrian Arab Republic' },
  { code: 'TW', name: 'Taiwan' },
  { code: 'TJ', name: 'Tajikistan' },
  { code: 'TZ', name: 'Tanzania, United Republic of' },
  { code: 'TH', name: 'Thailand' },
  { code: 'TL', name: 'Timor-Leste' },
  { code: 'TG', name: 'Togo' },
  { code: 'TK', name: 'Tokelau' },
  { code: 'TO', name: 'Tonga' },
  { code: 'TT', name: 'Trinidad and Tobago' },
  { code: 'TN', name: 'Tunisia' },
  { code: 'TR', name: 'Turkey' },
  { code: 'TM', name: 'Turkmenistan' },
  { code: 'TC', name: 'Turks and Caicos Islands' },
  { code: 'TV', name: 'Tuvalu' },
  { code: 'UG', name: 'Uganda' },
  { code: 'UA', name: 'Ukraine' },
  { code: 'AE', name: 'United Arab Emirates' },
  { code: 'GB', name: 'United Kingdom' },
  { code: 'UM', name: 'United States Minor Outlying Islands' },
  { code: 'US', name: 'United States of America' },
  { code: 'UY', name: 'Uruguay' },
  { code: 'UZ', name: 'Uzbekistan' },
  { code: 'VU', name: 'Vanuatu' },
  { code: 'VE', name: 'Venezuela' },
  { code: 'VN', name: 'Viet Nam' },
  { code: 'VG', name: 'Virgin Islands (British)' },
  { code: 'VI', name: 'Virgin Islands (U.S.)' },
  { code: 'WF', name: 'Wallis and Futuna' },
  { code: 'EH', name: 'Western Sahara' },
  { code: 'YE', name: 'Yemen' },
  { code: 'ZM', name: 'Zambia' },
  { code: 'ZW', name: 'Zimbabwe' },
];

/**
 * Country data with VAT rates and currency information
 */
export const COUNTRY_VAT_CURRENCY: Record<string, CountryData> = {
  US: { code: 'US', name: 'United States', currency: 'US Dollar', currencyCode: 'USD', vatRate: 0, currencySymbol: '$' },
  GB: { code: 'GB', name: 'United Kingdom', currency: 'British Pound', currencyCode: 'GBP', vatRate: 20, currencySymbol: '£' },
  DE: { code: 'DE', name: 'Germany', currency: 'Euro', currencyCode: 'EUR', vatRate: 19, currencySymbol: '€' },
  FR: { code: 'FR', name: 'France', currency: 'Euro', currencyCode: 'EUR', vatRate: 20, currencySymbol: '€' },
  IT: { code: 'IT', name: 'Italy', currency: 'Euro', currencyCode: 'EUR', vatRate: 22, currencySymbol: '€' },
  ES: { code: 'ES', name: 'Spain', currency: 'Euro', currencyCode: 'EUR', vatRate: 21, currencySymbol: '€' },
  NL: { code: 'NL', name: 'Netherlands', currency: 'Euro', currencyCode: 'EUR', vatRate: 21, currencySymbol: '€' },
  BE: { code: 'BE', name: 'Belgium', currency: 'Euro', currencyCode: 'EUR', vatRate: 21, currencySymbol: '€' },
  AT: { code: 'AT', name: 'Austria', currency: 'Euro', currencyCode: 'EUR', vatRate: 20, currencySymbol: '€' },
  CH: { code: 'CH', name: 'Switzerland', currency: 'Swiss Franc', currencyCode: 'CHF', vatRate: 8.1, currencySymbol: 'CHF' },
  SE: { code: 'SE', name: 'Sweden', currency: 'Swedish Krona', currencyCode: 'SEK', vatRate: 25, currencySymbol: 'kr' },
  NO: { code: 'NO', name: 'Norway', currency: 'Norwegian Krone', currencyCode: 'NOK', vatRate: 25, currencySymbol: 'kr' },
  DK: { code: 'DK', name: 'Denmark', currency: 'Danish Krone', currencyCode: 'DKK', vatRate: 25, currencySymbol: 'kr' },
  CA: { code: 'CA', name: 'Canada', currency: 'Canadian Dollar', currencyCode: 'CAD', vatRate: 5, currencySymbol: '$' },
  AU: { code: 'AU', name: 'Australia', currency: 'Australian Dollar', currencyCode: 'AUD', vatRate: 10, currencySymbol: '$' },
  JP: { code: 'JP', name: 'Japan', currency: 'Japanese Yen', currencyCode: 'JPY', vatRate: 10, currencySymbol: '¥' },
  CN: { code: 'CN', name: 'China', currency: 'Chinese Yuan', currencyCode: 'CNY', vatRate: 13, currencySymbol: '¥' },
  IN: { code: 'IN', name: 'India', currency: 'Indian Rupee', currencyCode: 'INR', vatRate: 18, currencySymbol: '₹' },
  BR: { code: 'BR', name: 'Brazil', currency: 'Brazilian Real', currencyCode: 'BRL', vatRate: 18, currencySymbol: 'R$' },
  MX: { code: 'MX', name: 'Mexico', currency: 'Mexican Peso', currencyCode: 'MXN', vatRate: 16, currencySymbol: '$' },
  ZA: { code: 'ZA', name: 'South Africa', currency: 'South African Rand', currencyCode: 'ZAR', vatRate: 15, currencySymbol: 'R' },
  SG: { code: 'SG', name: 'Singapore', currency: 'Singapore Dollar', currencyCode: 'SGD', vatRate: 8, currencySymbol: '$' },
  HK: { code: 'HK', name: 'Hong Kong', currency: 'Hong Kong Dollar', currencyCode: 'HKD', vatRate: 0, currencySymbol: '$' },
  AE: { code: 'AE', name: 'United Arab Emirates', currency: 'UAE Dirham', currencyCode: 'AED', vatRate: 5, currencySymbol: 'د.إ' },
  SA: { code: 'SA', name: 'Saudi Arabia', currency: 'Saudi Riyal', currencyCode: 'SAR', vatRate: 15, currencySymbol: '﷼' },
  KR: { code: 'KR', name: 'Korea, Republic of', currency: 'South Korean Won', currencyCode: 'KRW', vatRate: 10, currencySymbol: '₩' },
  TH: { code: 'TH', name: 'Thailand', currency: 'Thai Baht', currencyCode: 'THB', vatRate: 7, currencySymbol: '฿' },
  MY: { code: 'MY', name: 'Malaysia', currency: 'Malaysian Ringgit', currencyCode: 'MYR', vatRate: 6, currencySymbol: 'RM' },
  PH: { code: 'PH', name: 'Philippines', currency: 'Philippine Peso', currencyCode: 'PHP', vatRate: 12, currencySymbol: '₱' },
  ID: { code: 'ID', name: 'Indonesia', currency: 'Indonesian Rupiah', currencyCode: 'IDR', vatRate: 11, currencySymbol: 'Rp' },
  VN: { code: 'VN', name: 'Viet Nam', currency: 'Vietnamese Dong', currencyCode: 'VND', vatRate: 10, currencySymbol: '₫' },
  PK: { code: 'PK', name: 'Pakistan', currency: 'Pakistani Rupee', currencyCode: 'PKR', vatRate: 17, currencySymbol: '₨' },
  BD: { code: 'BD', name: 'Bangladesh', currency: 'Bangladeshi Taka', currencyCode: 'BDT', vatRate: 15, currencySymbol: '৳' },
  EG: { code: 'EG', name: 'Egypt', currency: 'Egyptian Pound', currencyCode: 'EGP', vatRate: 14, currencySymbol: 'E£' },
  NG: { code: 'NG', name: 'Nigeria', currency: 'Nigerian Naira', currencyCode: 'NGN', vatRate: 7.5, currencySymbol: '₦' },
  KE: { code: 'KE', name: 'Kenya', currency: 'Kenyan Shilling', currencyCode: 'KES', vatRate: 16, currencySymbol: 'KSh' },
  NZ: { code: 'NZ', name: 'New Zealand', currency: 'New Zealand Dollar', currencyCode: 'NZD', vatRate: 15, currencySymbol: '$' },
  IE: { code: 'IE', name: 'Ireland', currency: 'Euro', currencyCode: 'EUR', vatRate: 23, currencySymbol: '€' },
  PT: { code: 'PT', name: 'Portugal', currency: 'Euro', currencyCode: 'EUR', vatRate: 23, currencySymbol: '€' },
  GR: { code: 'GR', name: 'Greece', currency: 'Euro', currencyCode: 'EUR', vatRate: 24, currencySymbol: '€' },
  PL: { code: 'PL', name: 'Poland', currency: 'Polish Zloty', currencyCode: 'PLN', vatRate: 23, currencySymbol: 'zł' },
  CZ: { code: 'CZ', name: 'Czechia', currency: 'Czech Koruna', currencyCode: 'CZK', vatRate: 21, currencySymbol: 'Kč' },
  HU: { code: 'HU', name: 'Hungary', currency: 'Hungarian Forint', currencyCode: 'HUF', vatRate: 27, currencySymbol: 'Ft' },
  RO: { code: 'RO', name: 'Romania', currency: 'Romanian Leu', currencyCode: 'RON', vatRate: 19, currencySymbol: 'lei' },
  TR: { code: 'TR', name: 'Turkey', currency: 'Turkish Lira', currencyCode: 'TRY', vatRate: 18, currencySymbol: '₺' },
};

/**
 * Get country data by country code
 */
export function getCountryData(countryCode: string): CountryData | null {
  return COUNTRY_VAT_CURRENCY[countryCode] || null;
}
