export interface CountryData {
  code: string;
  name: string;
  currency?: string;
  currencyCode?: string;
  vatRate?: number;
  currencySymbol?: string;
}

export const countries: CountryData[] = [
  { code: 'AF', name: 'Afghanistan' },
  { code: 'AX', name: 'Åland Islands' },
  { code: 'AL', name: 'Albania' },
  { code: 'DZ', name: 'Algeria' },
  { code: 'AS', name: 'American Samoa' },
  { code: 'AD', name: 'Andorra' },
  { code: 'AO', name: 'Angola' },
  { code: 'AI', name: 'Anguilla' },
  { code: 'AQ', name: 'Antarctica' },
  { code: 'AG', name: 'Antigua and Barbuda' },
  { code: 'AR', name: 'Argentina' },
  { code: 'AM', name: 'Armenia' },
  { code: 'AW', name: 'Aruba' },
  { code: 'AU', name: 'Australia' },
  { code: 'AT', name: 'Austria' },
  { code: 'AZ', name: 'Azerbaijan' },
  { code: 'BS', name: 'Bahamas' },
  { code: 'BH', name: 'Bahrain' },
  { code: 'BD', name: 'Bangladesh' },
  { code: 'BB', name: 'Barbados' },
  { code: 'BY', name: 'Belarus' },
  { code: 'BE', name: 'Belgium' },
  { code: 'BZ', name: 'Belize' },
  { code: 'BJ', name: 'Benin' },
  { code: 'BM', name: 'Bermuda' },
  { code: 'BT', name: 'Bhutan' },
  { code: 'BO', name: 'Bolivia' },
  { code: 'BQ', name: 'Bonaire, Sint Eustatius and Saba' },
  { code: 'BA', name: 'Bosnia and Herzegovina' },
  { code: 'BW', name: 'Botswana' },
  { code: 'BV', name: 'Bouvet Island' },
  { code: 'BR', name: 'Brazil' },
  { code: 'IO', name: 'British Indian Ocean Territory' },
  { code: 'BN', name: 'Brunei Darussalam' },
  { code: 'BG', name: 'Bulgaria' },
  { code: 'BF', name: 'Burkina Faso' },
  { code: 'BI', name: 'Burundi' },
  { code: 'CV', name: 'Cabo Verde' },
  { code: 'KH', name: 'Cambodia' },
  { code: 'CM', name: 'Cameroon' },
  { code: 'CA', name: 'Canada' },
  { code: 'KY', name: 'Cayman Islands' },
  { code: 'CF', name: 'Central African Republic' },
  { code: 'TD', name: 'Chad' },
  { code: 'CL', name: 'Chile' },
  { code: 'CN', name: 'China' },
  { code: 'CX', name: 'Christmas Island' },
  { code: 'CC', name: 'Cocos (Keeling) Islands' },
  { code: 'CO', name: 'Colombia' },
  { code: 'KM', name: 'Comoros' },
  { code: 'CD', name: 'Congo, Democratic Republic of the' },
  { code: 'CG', name: 'Congo' },
  { code: 'CK', name: 'Cook Islands' },
  { code: 'CR', name: 'Costa Rica' },
  { code: 'HR', name: 'Croatia' },
  { code: 'CU', name: 'Cuba' },
  { code: 'CW', name: 'Curaçao' },
  { code: 'CY', name: 'Cyprus' },
  { code: 'CZ', name: 'Czechia' },
  { code: 'CI', name: 'Côte d\'Ivoire' },
  { code: 'DK', name: 'Denmark' },
  { code: 'DJ', name: 'Djibouti' },
  { code: 'DM', name: 'Dominica' },
  { code: 'DO', name: 'Dominican Republic' },
  { code: 'EC', name: 'Ecuador' },
  { code: 'EG', name: 'Egypt' },
  { code: 'SV', name: 'El Salvador' },
  { code: 'GQ', name: 'Equatorial Guinea' },
  { code: 'ER', name: 'Eritrea' },
  { code: 'EE', name: 'Estonia' },
  { code: 'SZ', name: 'Eswatini' },
  { code: 'ET', name: 'Ethiopia' },
  { code: 'FK', name: 'Falkland Islands (Malvinas)' },
  { code: 'FO', name: 'Faroe Islands' },
  { code: 'FJ', name: 'Fiji' },
  { code: 'FI', name: 'Finland' },
  { code: 'FR', name: 'France' },
  { code: 'GF', name: 'French Guiana' },
  { code: 'PF', name: 'French Polynesia' },
  { code: 'TF', name: 'French Southern Territories' },
  { code: 'GA', name: 'Gabon' },
  { code: 'GM', name: 'Gambia' },
  { code: 'GE', name: 'Georgia' },
  { code: 'DE', name: 'Germany' },
  { code: 'GH', name: 'Ghana' },
  { code: 'GI', name: 'Gibraltar' },
  { code: 'GR', name: 'Greece' },
  { code: 'GL', name: 'Greenland' },
  { code: 'GD', name: 'Grenada' },
  { code: 'GP', name: 'Guadeloupe' },
  { code: 'GU', name: 'Guam' },
  { code: 'GT', name: 'Guatemala' },
  { code: 'GG', name: 'Guernsey' },
  { code: 'GN', name: 'Guinea' },
  { code: 'GW', name: 'Guinea-Bissau' },
  { code: 'GY', name: 'Guyana' },
  { code: 'HT', name: 'Haiti' },
  { code: 'HM', name: 'Heard Island and McDonald Islands' },
  { code: 'VA', name: 'Holy See' },
  { code: 'HN', name: 'Honduras' },
  { code: 'HK', name: 'Hong Kong' },
  { code: 'HU', name: 'Hungary' },
  { code: 'IS', name: 'Iceland' },
  { code: 'IN', name: 'India' },
  { code: 'ID', name: 'Indonesia' },
  { code: 'IR', name: 'Iran' },
  { code: 'IQ', name: 'Iraq' },
  { code: 'IE', name: 'Ireland' },
  { code: 'IM', name: 'Isle of Man' },
  { code: 'IL', name: 'Israel' },
  { code: 'IT', name: 'Italy' },
  { code: 'JM', name: 'Jamaica' },
  { code: 'JP', name: 'Japan' },
  { code: 'JE', name: 'Jersey' },
  { code: 'JO', name: 'Jordan' },
  { code: 'KZ', name: 'Kazakhstan' },
  { code: 'KE', name: 'Kenya' },
  { code: 'KI', name: 'Kiribati' },
  { code: 'KP', name: 'Korea, Democratic People\'s Republic of' },
  { code: 'KR', name: 'Korea, Republic of' },
  { code: 'KW', name: 'Kuwait' },
  { code: 'KG', name: 'Kyrgyzstan' },
  { code: 'LA', name: 'Lao People\'s Democratic Republic' },
  { code: 'LV', name: 'Latvia' },
  { code: 'LB', name: 'Lebanon' },
  { code: 'LS', name: 'Lesotho' },
  { code: 'LR', name: 'Liberia' },
  { code: 'LY', name: 'Libya' },
  { code: 'LI', name: 'Liechtenstein' },
  { code: 'LT', name: 'Lithuania' },
  { code: 'LU', name: 'Luxembourg' },
  { code: 'MO', name: 'Macao' },
  { code: 'MG', name: 'Madagascar' },
  { code: 'MW', name: 'Malawi' },
  { code: 'MY', name: 'Malaysia' },
  { code: 'MV', name: 'Maldives' },
  { code: 'ML', name: 'Mali' },
  { code: 'MT', name: 'Malta' },
  { code: 'MH', name: 'Marshall Islands' },
  { code: 'MQ', name: 'Martinique' },
  { code: 'MR', name: 'Mauritania' },
  { code: 'MU', name: 'Mauritius' },
  { code: 'YT', name: 'Mayotte' },
  { code: 'MX', name: 'Mexico' },
  { code: 'FM', name: 'Micronesia, Federated States of' },
  { code: 'MD', name: 'Moldova' },
  { code: 'MC', name: 'Monaco' },
  { code: 'MN', name: 'Mongolia' },
  { code: 'ME', name: 'Montenegro' },
  { code: 'MS', name: 'Montserrat' },
  { code: 'MA', name: 'Morocco' },
  { code: 'MZ', name: 'Mozambique' },
  { code: 'MM', name: 'Myanmar' },
  { code: 'NA', name: 'Namibia' },
  { code: 'NR', name: 'Nauru' },
  { code: 'NP', name: 'Nepal' },
  { code: 'NL', name: 'Netherlands' },
  { code: 'NC', name: 'New Caledonia' },
  { code: 'NZ', name: 'New Zealand' },
  { code: 'NI', name: 'Nicaragua' },
  { code: 'NE', name: 'Niger' },
  { code: 'NG', name: 'Nigeria' },
  { code: 'NU', name: 'Niue' },
  { code: 'NF', name: 'Norfolk Island' },
  { code: 'MK', name: 'North Macedonia' },
  { code: 'MP', name: 'Northern Mariana Islands' },
  { code: 'NO', name: 'Norway' },
  { code: 'OM', name: 'Oman' },
  { code: 'PK', name: 'Pakistan' },
  { code: 'PW', name: 'Palau' },
  { code: 'PS', name: 'Palestine, State of' },
  { code: 'PA', name: 'Panama' },
  { code: 'PG', name: 'Papua New Guinea' },
  { code: 'PY', name: 'Paraguay' },
  { code: 'PE', name: 'Peru' },
  { code: 'PH', name: 'Philippines' },
  { code: 'PN', name: 'Pitcairn' },
  { code: 'PL', name: 'Poland' },
  { code: 'PT', name: 'Portugal' },
  { code: 'PR', name: 'Puerto Rico' },
  { code: 'QA', name: 'Qatar' },
  { code: 'RO', name: 'Romania' },
  { code: 'RU', name: 'Russian Federation' },
  { code: 'RW', name: 'Rwanda' },
  { code: 'RE', name: 'Réunion' },
  { code: 'BL', name: 'Saint Barthélemy' },
  { code: 'SH', name: 'Saint Helena, Ascension and Tristan da Cunha' },
  { code: 'KN', name: 'Saint Kitts and Nevis' },
  { code: 'LC', name: 'Saint Lucia' },
  { code: 'MF', name: 'Saint Martin (French part)' },
  { code: 'PM', name: 'Saint Pierre and Miquelon' },
  { code: 'VC', name: 'Saint Vincent and the Grenadines' },
  { code: 'WS', name: 'Samoa' },
  { code: 'SM', name: 'San Marino' },
  { code: 'ST', name: 'Sao Tome and Principe' },
  { code: 'SA', name: 'Saudi Arabia' },
  { code: 'SN', name: 'Senegal' },
  { code: 'RS', name: 'Serbia' },
  { code: 'SC', name: 'Seychelles' },
  { code: 'SL', name: 'Sierra Leone' },
  { code: 'SG', name: 'Singapore' },
  { code: 'SX', name: 'Sint Maarten (Dutch part)' },
  { code: 'SK', name: 'Slovakia' },
  { code: 'SI', name: 'Slovenia' },
  { code: 'SB', name: 'Solomon Islands' },
  { code: 'SO', name: 'Somalia' },
  { code: 'ZA', name: 'South Africa' },
  { code: 'GS', name: 'South Georgia and the South Sandwich Islands' },
  { code: 'SS', name: 'South Sudan' },
  { code: 'ES', name: 'Spain' },
  { code: 'LK', name: 'Sri Lanka' },
  { code: 'SD', name: 'Sudan' },
  { code: 'SR', name: 'Suriname' },
  { code: 'SJ', name: 'Svalbard and Jan Mayen' },
  { code: 'SE', name: 'Sweden' },
  { code: 'CH', name: 'Switzerland' },
  { code: 'SY', name: 'Syrian Arab Republic' },
  { code: 'TW', name: 'Taiwan' },
  { code: 'TJ', name: 'Tajikistan' },
  { code: 'TZ', name: 'Tanzania, United Republic of' },
  { code: 'TH', name: 'Thailand' },
  { code: 'TL', name: 'Timor-Leste' },
  { code: 'TG', name: 'Togo' },
  { code: 'TK', name: 'Tokelau' },
  { code: 'TO', name: 'Tonga' },
  { code: 'TT', name: 'Trinidad and Tobago' },
  { code: 'TN', name: 'Tunisia' },
  { code: 'TR', name: 'Turkey' },
  { code: 'TM', name: 'Turkmenistan' },
  { code: 'TC', name: 'Turks and Caicos Islands' },
  { code: 'TV', name: 'Tuvalu' },
  { code: 'UG', name: 'Uganda' },
  { code: 'UA', name: 'Ukraine' },
  { code: 'AE', name: 'United Arab Emirates' },
  { code: 'GB', name: 'United Kingdom' },
  { code: 'UM', name: 'United States Minor Outlying Islands' },
  { code: 'US', name: 'United States of America' },
  { code: 'UY', name: 'Uruguay' },
  { code: 'UZ', name: 'Uzbekistan' },
  { code: 'VU', name: 'Vanuatu' },
  { code: 'VE', name: 'Venezuela' },
  { code: 'VN', name: 'Viet Nam' },
  { code: 'VG', name: 'Virgin Islands (British)' },
  { code: 'VI', name: 'Virgin Islands (U.S.)' },
  { code: 'WF', name: 'Wallis and Futuna' },
  { code: 'EH', name: 'Western Sahara' },
  { code: 'YE', name: 'Yemen' },
  { code: 'ZM', name: 'Zambia' },
  { code: 'ZW', name: 'Zimbabwe' },
];

/**
 * Country data with VAT rates and currency information
 */
export const COUNTRY_VAT_CURRENCY: Record<string, CountryData> = {
  US: { code: 'US', name: 'United States', currency: 'US Dollar', currencyCode: 'USD', vatRate: 0, currencySymbol: '$' },
  GB: { code: 'GB', name: 'United Kingdom', currency: 'British Pound', currencyCode: 'GBP', vatRate: 20, currencySymbol: '£' },
  DE: { code: 'DE', name: 'Germany', currency: 'Euro', currencyCode: 'EUR', vatRate: 19, currencySymbol: '€' },
  FR: { code: 'FR', name: 'France', currency: 'Euro', currencyCode: 'EUR', vatRate: 20, currencySymbol: '€' },
  IT: { code: 'IT', name: 'Italy', currency: 'Euro', currencyCode: 'EUR', vatRate: 22, currencySymbol: '€' },
  ES: { code: 'ES', name: 'Spain', currency: 'Euro', currencyCode: 'EUR', vatRate: 21, currencySymbol: '€' },
  NL: { code: 'NL', name: 'Netherlands', currency: 'Euro', currencyCode: 'EUR', vatRate: 21, currencySymbol: '€' },
  BE: { code: 'BE', name: 'Belgium', currency: 'Euro', currencyCode: 'EUR', vatRate: 21, currencySymbol: '€' },
  AT: { code: 'AT', name: 'Austria', currency: 'Euro', currencyCode: 'EUR', vatRate: 20, currencySymbol: '€' },
  CH: { code: 'CH', name: 'Switzerland', currency: 'Swiss Franc', currencyCode: 'CHF', vatRate: 8.1, currencySymbol: 'CHF' },
  SE: { code: 'SE', name: 'Sweden', currency: 'Swedish Krona', currencyCode: 'SEK', vatRate: 25, currencySymbol: 'kr' },
  NO: { code: 'NO', name: 'Norway', currency: 'Norwegian Krone', currencyCode: 'NOK', vatRate: 25, currencySymbol: 'kr' },
  DK: { code: 'DK', name: 'Denmark', currency: 'Danish Krone', currencyCode: 'DKK', vatRate: 25, currencySymbol: 'kr' },
  CA: { code: 'CA', name: 'Canada', currency: 'Canadian Dollar', currencyCode: 'CAD', vatRate: 5, currencySymbol: '$' },
  AU: { code: 'AU', name: 'Australia', currency: 'Australian Dollar', currencyCode: 'AUD', vatRate: 10, currencySymbol: '$' },
  JP: { code: 'JP', name: 'Japan', currency: 'Japanese Yen', currencyCode: 'JPY', vatRate: 10, currencySymbol: '¥' },
  CN: { code: 'CN', name: 'China', currency: 'Chinese Yuan', currencyCode: 'CNY', vatRate: 13, currencySymbol: '¥' },
  IN: { code: 'IN', name: 'India', currency: 'Indian Rupee', currencyCode: 'INR', vatRate: 18, currencySymbol: '₹' },
  BR: { code: 'BR', name: 'Brazil', currency: 'Brazilian Real', currencyCode: 'BRL', vatRate: 18, currencySymbol: 'R$' },
  MX: { code: 'MX', name: 'Mexico', currency: 'Mexican Peso', currencyCode: 'MXN', vatRate: 16, currencySymbol: '$' },
  ZA: { code: 'ZA', name: 'South Africa', currency: 'South African Rand', currencyCode: 'ZAR', vatRate: 15, currencySymbol: 'R' },
  SG: { code: 'SG', name: 'Singapore', currency: 'Singapore Dollar', currencyCode: 'SGD', vatRate: 8, currencySymbol: '$' },
  HK: { code: 'HK', name: 'Hong Kong', currency: 'Hong Kong Dollar', currencyCode: 'HKD', vatRate: 0, currencySymbol: '$' },
  AE: { code: 'AE', name: 'United Arab Emirates', currency: 'UAE Dirham', currencyCode: 'AED', vatRate: 5, currencySymbol: 'د.إ' },
  SA: { code: 'SA', name: 'Saudi Arabia', currency: 'Saudi Riyal', currencyCode: 'SAR', vatRate: 15, currencySymbol: '﷼' },
  KR: { code: 'KR', name: 'Korea, Republic of', currency: 'South Korean Won', currencyCode: 'KRW', vatRate: 10, currencySymbol: '₩' },
  TH: { code: 'TH', name: 'Thailand', currency: 'Thai Baht', currencyCode: 'THB', vatRate: 7, currencySymbol: '฿' },
  MY: { code: 'MY', name: 'Malaysia', currency: 'Malaysian Ringgit', currencyCode: 'MYR', vatRate: 6, currencySymbol: 'RM' },
  PH: { code: 'PH', name: 'Philippines', currency: 'Philippine Peso', currencyCode: 'PHP', vatRate: 12, currencySymbol: '₱' },
  ID: { code: 'ID', name: 'Indonesia', currency: 'Indonesian Rupiah', currencyCode: 'IDR', vatRate: 11, currencySymbol: 'Rp' },
  VN: { code: 'VN', name: 'Viet Nam', currency: 'Vietnamese Dong', currencyCode: 'VND', vatRate: 10, currencySymbol: '₫' },
  PK: { code: 'PK', name: 'Pakistan', currency: 'Pakistani Rupee', currencyCode: 'PKR', vatRate: 17, currencySymbol: '₨' },
  BD: { code: 'BD', name: 'Bangladesh', currency: 'Bangladeshi Taka', currencyCode: 'BDT', vatRate: 15, currencySymbol: '৳' },
  EG: { code: 'EG', name: 'Egypt', currency: 'Egyptian Pound', currencyCode: 'EGP', vatRate: 14, currencySymbol: 'E£' },
  NG: { code: 'NG', name: 'Nigeria', currency: 'Nigerian Naira', currencyCode: 'NGN', vatRate: 7.5, currencySymbol: '₦' },
  KE: { code: 'KE', name: 'Kenya', currency: 'Kenyan Shilling', currencyCode: 'KES', vatRate: 16, currencySymbol: 'KSh' },
  NZ: { code: 'NZ', name: 'New Zealand', currency: 'New Zealand Dollar', currencyCode: 'NZD', vatRate: 15, currencySymbol: '$' },
  IE: { code: 'IE', name: 'Ireland', currency: 'Euro', currencyCode: 'EUR', vatRate: 23, currencySymbol: '€' },
  PT: { code: 'PT', name: 'Portugal', currency: 'Euro', currencyCode: 'EUR', vatRate: 23, currencySymbol: '€' },
  GR: { code: 'GR', name: 'Greece', currency: 'Euro', currencyCode: 'EUR', vatRate: 24, currencySymbol: '€' },
  PL: { code: 'PL', name: 'Poland', currency: 'Polish Zloty', currencyCode: 'PLN', vatRate: 23, currencySymbol: 'zł' },
  CZ: { code: 'CZ', name: 'Czechia', currency: 'Czech Koruna', currencyCode: 'CZK', vatRate: 21, currencySymbol: 'Kč' },
  HU: { code: 'HU', name: 'Hungary', currency: 'Hungarian Forint', currencyCode: 'HUF', vatRate: 27, currencySymbol: 'Ft' },
  RO: { code: 'RO', name: 'Romania', currency: 'Romanian Leu', currencyCode: 'RON', vatRate: 19, currencySymbol: 'lei' },
  TR: { code: 'TR', name: 'Turkey', currency: 'Turkish Lira', currencyCode: 'TRY', vatRate: 18, currencySymbol: '₺' },
};

/**
 * Get country data by country code
 */
export function getCountryData(countryCode: string): CountryData | null {
  return COUNTRY_VAT_CURRENCY[countryCode] || null;
}
